/**
 * Native pgAdmin schema-diff engine. `db diff` is the only caller, so this stays
 * colocated with the command rather than under `commands/db/shared/`; move it
 * there (and split the error into its own `legacy-pgadmin-diff.errors.ts`,
 * mirroring `legacy-migra.ts`/`legacy-migra.errors.ts`) if a second command ever
 * needs it.
 *
 * Covers the two pure halves — parsing (`legacyParsePgAdminDiffEntries`) and
 * rendering (`legacyRenderPgAdminDiff`), recomposed as
 * `legacyProcessPgAdminDiffOutput` for a single whole buffer — and the
 * container-invocation loop, `legacyDiffSchemaPgAdmin`. Shadow provisioning, the
 * `Creating shadow database...`/`Diffing local database with current
 * migrations...` status lines, and the file write all stay in `diff.handler.ts`.
 *
 * **Deliberate divergence from the historical Go implementation:** the differ
 * container's stdout was, in the original Go CLI, never actually collected — a
 * struct-copy bug meant `--use-pgadmin` always reported "No schema changes found"
 * (exit 0) regardless of the differ's real output, on any schema count. This port
 * implements the algorithm the surrounding code clearly intended: it parses EACH
 * run's own real stdout separately and aggregates the kept DDLs across runs,
 * rather than gluing every run's raw bytes into one buffer and parsing that once
 * (which would turn a multi-`--schema` diff whose every run individually parses
 * fine into a spurious `JSON.parse` "trailing data" failure — the worst of both
 * worlds). So where the historical implementation silently reported an empty diff
 * no matter what the differ produced, this port produces the actual, aggregated
 * diff across every run (or a real per-run JSON-parse error — see
 * `legacyParsePgAdminDiffEntries`'s own doc comment). Ruling: keep this port's
 * (correct) implementation; see `SIDE_EFFECTS.md`'s "Deliberate divergence" entry
 * for the user-facing framing.
 */

import { Effect, Option, Result } from "effect";

import { dockerfileServiceImage } from "../../../../shared/services/dockerfile-images.ts";
import { LEGACY_COMPOSE_PROJECT_LABEL } from "../../../shared/db-bootstrap/container-lifecycle.ts";
import { LEGACY_CLI_PROJECT_LABEL } from "../../../shared/legacy-docker-ids.ts";
import { LegacyDockerRun } from "../../../shared/legacy-docker-run.service.ts";
import { legacyTrimGoSpace } from "../shared/legacy-go-string.ts";
import { LEGACY_INTERNAL_SCHEMAS } from "../../../shared/legacy-pg-dump.env.ts";
import { LegacyDbDiffPgAdminError } from "./diff.errors.ts";

const LEGACY_DIFFER_IMAGE = dockerfileServiceImage("differ");

/**
 * Trimmed front-anchored only (not a global strip) — a real pgAdmin4 output quirk
 * (`supabase/pgadmin4#24`). `legacyParsePgAdminDiffEntries` runs once per differ
 * run, so each run's OWN copy of this note is trimmed off the front of that run's
 * own buffer; `legacyProcessPgAdminDiffOutput`, applied to a single whole buffer,
 * still only strips the very front of whatever string it's given.
 */
export const LEGACY_PGADMIN_DESKTOP_NOTE_PREFIX =
  "NOTE: Configuring authentication for DESKTOP mode.\n";

/** Prepended verbatim to every rendered diff (established output contract). */
export const LEGACY_PGADMIN_DIFF_HEADER = `-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.`;

/** Allow-list of `DiffEntry.type` values kept in the diff. */
const LEGACY_PGADMIN_DIFF_TYPES = new Set([
  "extension",
  "function",
  "mview",
  "table",
  "trigger_function",
  "type",
  "view",
]);

/**
 * Compiled with the `s` (dotAll) flag: JS's `.` excludes every line-terminator code
 * point (`\r`, `\n`, U+2028, U+2029) unless `s` is set, and `legacyScanLines` only
 * splits on `\n`, so a line can still carry embedded `\r`s from a `\r`-driven
 * progress bar (multiple updates overwriting the same terminal line) — without `s`,
 * this pattern would stop matching at the first embedded `\r`. No alternation, so
 * the match is greedy on the digit/percent suffix, e.g. `"Diffing 100%"` → group 1
 * `"Diffing 1"`, group 2 `"00"`.
 */
const LEGACY_PGADMIN_PROGRESS_RE = /(.*)([0-9]{2,3})%/s;

/**
 * Splits `stderr` into lines: `\r\n`/`\n`-terminated lines with the trailing `\r`
 * (if any) stripped, and a final, non-newline-terminated fragment still emitted as
 * its own line. An empty input yields zero lines. Deliberately has no line-length
 * limit, so an abnormally long differ progress line is still scanned in full.
 */
function legacyScanLines(text: string): ReadonlyArray<string> {
  if (text.length === 0) return [];
  const lines = text.split("\n");
  // A trailing `\n` produces one trailing empty element from `split` that isn't a
  // real line of its own — the `\n` itself already terminated the prior line.
  const withoutTrailingNewline = text.endsWith("\n") ? lines.slice(0, -1) : lines;
  return withoutTrailingNewline.map((line) => (line.endsWith("\r") ? line.slice(0, -1) : line));
}

/**
 * Extracts the status lines from the differ's stderr progress stream (progress
 * percentages themselves are dropped). `"Starting schema diff..."` and any
 * non-matching line produce nothing. This port's stdout emission
 * (`diff.handler.ts`'s `emitStatus`) targets non-TTY status-line output; a TTY
 * session's frame-by-frame progress rendering has no TS equivalent.
 */
export function legacyProcessPgAdminDiffProgress(stderr: string): ReadonlyArray<string> {
  const statuses: Array<string> = [];
  for (const line of legacyScanLines(stderr)) {
    const match = LEGACY_PGADMIN_PROGRESS_RE.exec(line);
    if (match === null) continue;
    statuses.push(match[1] ?? "");
  }
  return statuses;
}

/**
 * Field kept snake_case (the literal wire key), not camelCased, so the guard
 * below reads the parsed JSON 1:1.
 */
interface LegacyPgAdminDiffDependency {
  readonly type?: string | null;
}

/** One `--json-diff` array element. */
interface LegacyPgAdminDiffEntry {
  readonly type?: string | null;
  readonly status?: string | null;
  readonly diff_ddl?: string | null;
  readonly group_name?: string | null;
  readonly dependencies?: ReadonlyArray<LegacyPgAdminDiffDependency | null> | null;
  readonly source_schema_name?: string | null;
}

/**
 * A present field's type is checked exactly like every other `DiffEntry` scalar
 * below — see {@link legacyIsPgAdminDiffEntryElement}'s own doc comment for the
 * shared "null tolerated per field" rule.
 */
function legacyIsPgAdminDiffDependencyElement(
  value: unknown,
): value is LegacyPgAdminDiffDependency | null {
  if (value === null) return true;
  if (typeof value !== "object" || Array.isArray(value)) return false;
  if ("type" in value && value.type !== null && typeof value.type !== "string") return false;
  return true;
}

/**
 * Structural guard for the differ's `DiffEntry` JSON shape, applied to an
 * untrusted `JSON.parse` of the differ's stdout:
 * - a bare `null` array element is accepted — the caller normalizes it away
 *   before this guard ever sees it;
 * - a non-null, non-object element (`{}`/`"x"`/`1`/`true`/an array) is rejected;
 * - `null` for an individual DECLARED scalar field (`type`/`status`/`diff_ddl`/
 *   `group_name`/`source_schema_name`) is tolerated with no error, leaving the
 *   zero value — so `{"status":null}` is accepted, not rejected;
 * - a MISTYPED declared field (`{"type":123}`, `{"dependencies":{}}`,
 *   `{"dependencies":[1]}`, a `dependencies[].type` that isn't a string) is
 *   rejected, so every array field's own elements are validated too, not just
 *   its own top-level shape.
 */
function legacyIsPgAdminDiffEntryElement(value: unknown): value is LegacyPgAdminDiffEntry | null {
  if (value === null) return true;
  if (typeof value !== "object" || Array.isArray(value)) return false;
  if ("type" in value && value.type !== null && typeof value.type !== "string") return false;
  if ("status" in value && value.status !== null && typeof value.status !== "string") return false;
  if ("diff_ddl" in value && value.diff_ddl !== null && typeof value.diff_ddl !== "string") {
    return false;
  }
  if ("group_name" in value && value.group_name !== null && typeof value.group_name !== "string") {
    return false;
  }
  if (
    "source_schema_name" in value &&
    value.source_schema_name !== null &&
    typeof value.source_schema_name !== "string"
  ) {
    return false;
  }
  if ("dependencies" in value && value.dependencies !== null) {
    if (
      !Array.isArray(value.dependencies) ||
      !value.dependencies.every(legacyIsPgAdminDiffDependencyElement)
    ) {
      return false;
    }
  }
  return true;
}

/**
 * Parse/filter half of the differ output pipeline — pure, no Effect. Trims the
 * DESKTOP-mode NOTE prefix off the FRONT of `stdout` (a real pgAdmin4 quirk,
 * `supabase/pgadmin4#24`), then parses and filters it into the ordered list of
 * kept, trimmed DDL strings (allow-listed entry types + internal-schema/
 * extension-dependency filtering). Rendering the header and joining is
 * `legacyRenderPgAdminDiff`'s job, kept separate so `legacyDiffSchemaPgAdmin`'s
 * run loop can parse EACH run's own buffer (trimming that run's own DESKTOP-mode
 * note, if any) and aggregate every run's DDLs before rendering once — avoiding
 * gluing raw bytes together first, which would turn a multi-`--schema` diff where
 * every run individually parses fine into one spurious `JSON.parse` "trailing
 * data" failure.
 */
export function legacyParsePgAdminDiffEntries(
  stdout: string,
): Result.Result<ReadonlyArray<string>, { readonly message: string }> {
  const trimmed = stdout.startsWith(LEGACY_PGADMIN_DESKTOP_NOTE_PREFIX)
    ? stdout.slice(LEGACY_PGADMIN_DESKTOP_NOTE_PREFIX.length)
    : stdout;
  if (trimmed.length === 0) return Result.succeed([]);

  let parsed: unknown;
  try {
    parsed = JSON.parse(trimmed);
  } catch (cause) {
    return Result.fail({
      message: `failed to parse schema diff output: ${cause instanceof Error ? cause.message : String(cause)}`,
    });
  }
  // `json.Unmarshal` into a non-pointer `[]DiffEntry` accepts a top-level JSON `null` as a
  // no-op (nil slice) — normalize it to `[]` before the array guard below, matching
  // `legacyIsPgDeltaApplyResult`'s identical `null` handling.
  const entries: unknown = parsed === null ? [] : parsed;
  if (!Array.isArray(entries) || !entries.every(legacyIsPgAdminDiffEntryElement)) {
    return Result.fail({
      message: "failed to parse schema diff output: not a valid schema-diff entry array",
    });
  }

  const filteredDdls: Array<string> = [];
  for (const rawEntry of entries) {
    const entry = rawEntry ?? {};
    const status = entry.status ?? "";
    const diffDdl = entry.diff_ddl ?? "";
    if (status === "Identical" || diffDdl === "") continue;
    if (!LEGACY_PGADMIN_DIFF_TYPES.has(entry.type ?? "")) continue;
    const dependencies = entry.dependencies ?? [];
    if (dependencies.some((dep) => (dep?.type ?? "") === "extension")) continue;
    const groupName = entry.group_name ?? "";
    const sourceSchemaName = entry.source_schema_name ?? undefined;
    if (
      LEGACY_INTERNAL_SCHEMAS.includes(groupName) ||
      (sourceSchemaName !== undefined && LEGACY_INTERNAL_SCHEMAS.includes(sourceSchemaName))
    ) {
      continue;
    }
    const trimmedDdl = legacyTrimGoSpace(diffDdl);
    if (trimmedDdl.length > 0) filteredDdls.push(trimmedDdl);
  }

  return Result.succeed(filteredDdls);
}

/** Header-plus-join half of the differ output pipeline. */
export function legacyRenderPgAdminDiff(ddls: ReadonlyArray<string>): string {
  if (ddls.length === 0) return "";
  return `${LEGACY_PGADMIN_DIFF_HEADER}\n\n${ddls.join("\n\n")}\n`;
}

/**
 * Parse-then-render composition of the two halves above, applied to a SINGLE,
 * whole buffer — kept for callers (and this file's own unit tests) that want the
 * whole pipeline as one function over one buffer. `legacyDiffSchemaPgAdmin`'s run
 * loop calls `legacyParsePgAdminDiffEntries`/`legacyRenderPgAdminDiff` directly
 * instead, once per run, so this function's own single-buffer semantics
 * (including the multi-JSON-array "trailing data" failure on a buffer that
 * concatenates >=1 complete arrays) are unchanged but no longer reachable from a
 * multi-`--schema` diff.
 */
export function legacyProcessPgAdminDiffOutput(
  stdout: string,
): Result.Result<string, { readonly message: string }> {
  return Result.map(legacyParsePgAdminDiffEntries(stdout), legacyRenderPgAdminDiff);
}

/**
 * Maps `LegacyDockerRunError`'s own three-way docker-boundary discriminant onto this
 * command's `reason` union — mirrors `legacyDbSetupDockerReason` (`db-setup.ts`): a spawn
 * failure or a detected daemon-down message means the daemon itself is unreachable, a failed
 * image inspect is a config/registry-availability issue distinct from a pull failure, and
 * everything else at this boundary is a registry-pull failure. `diffMigraBash`
 * (`legacy-migra.ts`) keeps its own pre-existing two-way collapse (`inspect` folded into
 * `pull`) — out of scope for this port.
 */
function legacyPgAdminDockerReason(
  reason: "spawn" | "inspect" | "pull",
  daemonDown: boolean,
): "docker_daemon" | "image_inspect" | "registry_pull" {
  if (reason === "spawn" || daemonDown) return "docker_daemon";
  if (reason === "pull") return "registry_pull";
  return "image_inspect";
}

export interface LegacyDiffSchemaPgAdminParams {
  /** The USER'S db. */
  readonly source: string;
  /** The SHADOW — a raw connection string, not built via `legacyToPostgresURL`. */
  readonly target: string;
  readonly schema: ReadonlyArray<string>;
  /** Merged onto both docker labels, matching every other container this codebase creates. */
  readonly projectId: string;
  /**
   * Already `--network-id`/`SUPABASE_NETWORK_ID`/`supabase_network_<projectId>`-resolved by
   * the caller (`legacyResolveNetworkId`, via `legacyBuildLocalDbContainerInputs`'s
   * `localInputs.networkId`) — never empty, so this function does no second resolution and,
   * unlike `legacy-migra.ts`'s `diffMigraBash`, never falls back to a host network: the
   * differ always joins a user-defined bridge network.
   */
  readonly networkId: string;
  /** Linux-only `host.docker.internal:host-gateway`; empty elsewhere. */
  readonly extraHosts: ReadonlyArray<string>;
  /** Text-mode stdout sink for the `Diffing schema: <s>` / progress status lines; no-op in machine output modes. */
  readonly emitStatus: (line: string) => Effect.Effect<void>;
}

/**
 * One differ container run when no `--schema` is given, else one run per
 * `--schema` (in flag order), each preceded by its own `Diffing schema: <s>`
 * status. `runCapture`, not `runStream`, because the differ's progress lines
 * arrive on STDERR, and `LegacyDockerRun.runStream` only exposes an `onStdout`
 * streaming hook — there is no `onStderr` equivalent to observe stderr
 * incrementally through this service today. This means status lines aren't
 * live-streamed: this function buffers each run's stderr in full via
 * `runCapture` and only filters/flushes it (`legacyProcessPgAdminDiffProgress` +
 * `emitStatus`, below) once that run's container has already exited — so a
 * multi-`--schema` diff still gets one status batch per run, but within a single
 * run every one of its status lines appears together, after the fact, instead
 * of as the differ actually emits them. A real fix would add an `onStderr`
 * streaming hook to `runStream`, mirroring `onStdout`, and switch this function
 * to it. `teeStderr` stays off regardless. The image is passed raw (not
 * pre-resolved via `legacyGetRegistryImageUrl`, unlike `diffMigraBash`):
 * `legacyDockerRunLayer`'s own resolver builds the ECR→GHCR→docker.io candidate
 * ladder from it — reading `SUPABASE_INTERNAL_IMAGE_REGISTRY` straight off
 * `process.env` at call time (no `projectEnvValues` passed through). It is the
 * caller's (`diff.handler.ts`) own `legacyApplyProjectEnv` scope, applied right
 * after the config load, that makes a registry override set only in the
 * project's `supabase/.env` (not the ambient shell) visible to that resolver by
 * the time this function's `runCapture` call reaches it.
 */
export const legacyDiffSchemaPgAdmin = (
  params: LegacyDiffSchemaPgAdminParams,
): Effect.Effect<string, LegacyDbDiffPgAdminError, LegacyDockerRun> =>
  Effect.gen(function* () {
    const docker = yield* LegacyDockerRun;
    const labels = {
      [LEGACY_CLI_PROJECT_LABEL]: params.projectId,
      [LEGACY_COMPOSE_PROJECT_LABEL]: params.projectId,
    };
    const network = { _tag: "named" as const, name: params.networkId };
    const runs: ReadonlyArray<string | undefined> =
      params.schema.length === 0 ? [undefined] : params.schema;

    const ddls: Array<string> = [];
    for (const s of runs) {
      if (s !== undefined) yield* params.emitStatus(`Diffing schema: ${s}`);
      const cmd =
        s === undefined
          ? ["--json-diff", params.source, params.target]
          : ["--schema", s, "--json-diff", params.source, params.target];
      const result = yield* docker
        .runCapture({
          image: LEGACY_DIFFER_IMAGE,
          cmd,
          env: {},
          binds: [],
          workingDir: Option.none(),
          securityOpt: [],
          extraHosts: params.extraHosts,
          network,
          labels,
        })
        .pipe(
          Effect.mapError(
            (cause) =>
              new LegacyDbDiffPgAdminError({
                message: cause.message,
                reason: legacyPgAdminDockerReason(cause.reason, cause.daemonDown),
              }),
          ),
        );
      // Emitted BEFORE the exit-code check below: a failed run's own status lines
      // should still print ahead of the container error surfacing. Returning early
      // on a nonzero exit before reaching this would silently drop that run's
      // already-captured statuses.
      for (const line of legacyProcessPgAdminDiffProgress(result.stderr)) {
        yield* params.emitStatus(line);
      }
      if (result.exitCode !== 0) {
        // The differ's own stderr is never surfaced beyond the progress-line
        // filter above; any non-matching line is silently dropped, even under
        // `--debug`.
        return yield* new LegacyDbDiffPgAdminError({
          message: `error running container: exit ${result.exitCode}`,
          reason: "differ",
        });
      }
      const stdout = new TextDecoder().decode(result.stdout);
      // Parsed per run rather than concatenated across runs and parsed once,
      // which would turn a multi-`--schema` diff whose every run individually
      // parses fine into a spurious "trailing data" `JSON.parse` failure — see
      // this module's own header comment.
      const parsed = legacyParsePgAdminDiffEntries(stdout);
      if (Result.isFailure(parsed)) {
        return yield* new LegacyDbDiffPgAdminError({
          message: parsed.failure.message,
          reason: "invalid_output",
        });
      }
      ddls.push(...parsed.success);
    }

    return legacyRenderPgAdminDiff(ddls);
  });
