export const SCHEMA_DIRECTORY_NAME = "schemas";
export const SCHEMA_CUSTOM_DIRECTORY_NAME = "_custom";
export const SCHEMA_CHECKPOINT_FILE_NAME = ".schema-checkpoint.json";
export const SCHEMA_DRAFT_JOURNAL_FILE_NAME = "schema-draft.json";
export const SCHEMA_LOCK_FILE_NAME = "schema.lock";
export const MIGRATIONS_DIRECTORY_NAME = "migrations";
export const SCHEMA_ARTIFACT_FORMAT_VERSION = 1;
export const SCHEMA_PROFILE_ID = "supabase";
export const SCHEMA_MANAGEMENT_SCOPE = "database";
export const MIGRATION_NO_TRANSACTION_DIRECTIVE = "-- pg-delta: transaction=false";
export const MIGRATE_FILE_PATTERN = /^([0-9]+)_(.*)\.sql$/u;
