import { NodeRuntime, NodeServices } from "@effect/platform-node";
import { build, stop } from "esbuild";
import { Data, Effect, FileSystem, Path } from "effect";

class FunctionsBootstrapBundleError extends Data.TaggedError("FunctionsBootstrapBundleError")<{
  readonly message: string;
  readonly cause?: unknown;
}> {}

const packageRoot = Effect.gen(function* () {
  const path = yield* Path.Path;
  return path.dirname(path.dirname(yield* path.fromFileUrl(new URL(import.meta.url))));
});

/** Location of the committed default Functions bootstrap module. */
export const generatedModulePath = Effect.gen(function* () {
  const path = yield* Path.Path;
  return path.join(yield* packageRoot, "src", "functions", "generated", "serve-main-bundle.ts");
});

const bundleServeMain = Effect.gen(function* () {
  const path = yield* Path.Path;
  const entrypoint = path.join(yield* packageRoot, "src", "functions", "serve.main.ts");
  const result = yield* Effect.tryPromise({
    try: () =>
      build({
        entryPoints: [entrypoint],
        bundle: true,
        format: "esm",
        platform: "browser",
        minify: true,
        write: false,
        legalComments: "none",
        logLevel: "silent",
      }),
    catch: (cause) =>
      new FunctionsBootstrapBundleError({ message: "Unable to bundle functions bootstrap", cause }),
  });
  const output = result.outputFiles[0]?.text;
  if (output === undefined)
    return yield* new FunctionsBootstrapBundleError({
      message: "esbuild produced no functions bootstrap output",
    });
  return output;
}).pipe((program) =>
  Effect.uninterruptibleMask((restore) =>
    Effect.flatMap(Effect.exit(restore(program)), (result) =>
      Effect.tryPromise({
        try: () => stop(),
        catch: (cause) =>
          new FunctionsBootstrapBundleError({ message: "Unable to stop esbuild", cause }),
      }).pipe(Effect.andThen(result)),
    ),
  ),
);

/** Renders the generated module that embeds the self-contained Edge Runtime main service. */
export const renderFunctionsBootstrapModule = Effect.map(
  bundleServeMain,
  (bundle) =>
    "// Generated by packages/stack/scripts/generate-functions-bootstrap.ts; run `pnpm generate`.\n" +
    "/** Bundled Edge Runtime main service used when a Functions creation has no bootstrap. */\n" +
    `export const defaultFunctionsBootstrap = ${JSON.stringify(bundle)};\n`,
);

if (import.meta.main)
  NodeRuntime.runMain(
    Effect.gen(function* () {
      const fs = yield* FileSystem.FileSystem;
      const path = yield* Path.Path;
      const target = yield* generatedModulePath;
      const source = yield* renderFunctionsBootstrapModule;
      yield* fs.makeDirectory(path.dirname(target), { recursive: true });
      yield* fs.writeFileString(target, source);
    }).pipe(Effect.provide(NodeServices.layer)),
  );
