version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 0 * * *"
    groups:
      actions-major:
        patterns:
          - "*"
    ignore:
      - dependency-name: "supabase/setup-cli"
        update-types:
          - "version-update:semver-major"
    cooldown:
      default-days: 7
  - package-ecosystem: "gomod"
    directories:
      - "/apps/cli-go"
      - "/apps/cli-go/pkg"
    schedule:
      interval: "cron"
      cronjob: "0 0 * * *"
    groups:
      go-minor:
        update-types:
          - minor
          - patch
        exclude-patterns:
          - github.com/compose-spec/compose-go/v2
    cooldown:
      default-days: 7
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 0 * * *"
    groups:
      npm-major:
        patterns:
          - "*"
    cooldown:
      default-days: 7
  - package-ecosystem: "docker"
    directory: "/apps/cli-go/pkg/config/templates"
    schedule:
      interval: "cron"
      cronjob: "0 0 * * *"
    commit-message:
      prefix: "fix(docker): "
    groups:
      docker-minor:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "library/kong"
      - dependency-name: "axllent/mailpit"
      - dependency-name: "darthsim/imgproxy"
      - dependency-name: "timberio/vector"
    cooldown:
      default-days: 7
      exclude:
        - "supabase/*"
