import { mkdir, readdir, unlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { expect } from "vitest";

import {
  liveDatabaseTargetArgs,
  requireLiveSuccess,
  test,
} from "../../../../../tests/helpers/live.ts";

test("pulls the remote schema after a local migration is applied", async ({
  run,
  dbUrl,
  projectRef,
  workspace,
}) => {
  const version = `${Date.now()}${Math.floor(Math.random() * 10_000)
    .toString()
    .padStart(4, "0")}`;
  const migrations = join(workspace.path, "supabase", "migrations");
  await mkdir(migrations, { recursive: true });
  const existingMigrations = new Set(await readdir(migrations));
  const migrationFile = join(migrations, `${version}_e2e_pull.sql`);
  await writeFile(migrationFile, `create table if not exists e2e_pull_${version} (id int);\n`);

  let targetError: unknown;
  try {
    const pushed = await run(["db", "push", ...liveDatabaseTargetArgs(dbUrl, projectRef), "--yes"]);
    requireLiveSuccess(pushed, "db push setup");

    const result = await run(["db", "pull", ...liveDatabaseTargetArgs(dbUrl, projectRef), "--yes"]);
    expect(result.exitCode, result.stderr).toBe(0);
    expect(`${result.stdout}${result.stderr}`).not.toMatch(
      /dial|no route|connection refused|could not connect|server closed the connection|i\/o timeout/i,
    );
  } catch (error) {
    targetError = error;
  }

  let cleanupError: unknown;
  try {
    // Remove all migrations created by this test before resetting. This
    // includes both the seed migration and the migration generated by
    // `db pull`; resetting with only the generated grant statements left
    // behind can reference a table that no longer exists.
    const currentMigrations = await readdir(migrations).catch(() => []);
    for (const file of currentMigrations.filter(
      (candidate) => !existingMigrations.has(candidate),
    )) {
      try {
        await unlink(join(migrations, file));
      } catch (error) {
        throw new Error(
          `db pull cleanup could not remove test migration ${join(migrations, file)}: ${
            error instanceof Error ? error.message : String(error)
          }`,
        );
      }
    }

    const reset = await run(["db", "reset", ...liveDatabaseTargetArgs(dbUrl, projectRef), "--yes"]);
    requireLiveSuccess(reset, "db reset cleanup after db pull");
  } catch (error) {
    cleanupError = error;
  }

  if (targetError !== undefined) {
    throw targetError;
  }
  if (cleanupError !== undefined) {
    throw cleanupError;
  }
});
