import { mkdir, readdir, unlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { expect } from "vitest";

import { requireLiveSuccess, test, throwWithCleanup } from "../../../../../tests/helpers/live.ts";

test("pulls the remote schema after a local migration is applied", async ({
  cli,
  project,
  workspace,
}) => {
  const version = `${Date.now()}${Math.floor(Math.random() * 10_000)
    .toString()
    .padStart(4, "0")}`;
  const migrations = join(workspace.path, "supabase", "migrations");
  await mkdir(migrations, { recursive: true });
  const existingMigrations = new Set(await readdir(migrations));
  const migrationFile = join(migrations, `${version}_e2e_pull.sql`);
  await writeFile(migrationFile, `create table if not exists e2e_pull_${version} (id int);\n`);

  let targetError: unknown;
  try {
    const pushed = await cli(["db", "push", "--db-url", project.dbUrl, "--yes"]);
    requireLiveSuccess(pushed, "db push setup");

    const result = await cli(["db", "pull", "--db-url", project.dbUrl, "--yes"]);
    expect(result.exitCode, result.stderr).toBe(0);
    expect(`${result.stdout}${result.stderr}`).not.toMatch(
      /dial|no route|connection refused|could not connect|server closed the connection|i\/o timeout/i,
    );
  } catch (error) {
    targetError = error;
  }

  const cleanupErrors: Array<unknown> = [];
  // Remove all migrations created by this test before resetting. This
  // includes both the seed migration and the migration generated by
  // `db pull`; resetting with only the generated grant statements left
  // behind can reference a table that no longer exists.
  let currentMigrations: ReadonlyArray<string> = [];
  try {
    currentMigrations = await readdir(migrations);
  } catch (error) {
    cleanupErrors.push(error);
  }
  for (const file of currentMigrations.filter((candidate) => !existingMigrations.has(candidate))) {
    try {
      await unlink(join(migrations, file));
    } catch (error) {
      cleanupErrors.push(
        new Error(
          `db pull cleanup could not remove test migration ${join(migrations, file)}: ${
            error instanceof Error ? error.message : String(error)
          }`,
        ),
      );
    }
  }

  try {
    const reset = await cli(["db", "reset", "--db-url", project.dbUrl, "--yes"]);
    requireLiveSuccess(reset, "db reset cleanup after db pull");
  } catch (error) {
    cleanupErrors.push(error);
  }

  throwWithCleanup(targetError, cleanupErrors);
});
