version: "2"
linters:
  enable:
    - dogsled
    - dupl
    - gosec
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    dupl:
      threshold: 250
  exclusions:
    generated: lax
    rules:
      - text: 'ST1003:'
        linters:
          - staticcheck
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
