project_name: supabase
builds:
  - id: supabase
    binary: supabase
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/supabase/cli/internal/utils.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
release:
  draft: true
  replace_existing_draft: true
  prerelease: auto
changelog:
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
brews:
  - name: supabase-beta
    tap:
      owner: supabase
      name: homebrew-tap
      token: "{{ .Env.BREWTAP_TOKEN }}"
    commit_author:
      name: Bobbie Soedirgo
      email: bobbie@soedirgo.dev
    url_template: "https://github.com/supabase/cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: https://supabase.com
    description: Supabase CLI (Beta)
    license: MIT
    install: |
      bin.install "supabase"
      (bash_completion/"supabase").write `#{bin}/supabase completion bash`
      (fish_completion/"supabase.fish").write `#{bin}/supabase completion fish`
      (zsh_completion/"_supabase").write `#{bin}/supabase completion zsh`
scoops:
  - name: supabase-beta
    bucket:
      owner: supabase
      name: scoop-bucket
      token: "{{ .Env.SCOOP_TOKEN }}"
    commit_author:
      name: Bobbie Soedirgo
      email: bobbie@soedirgo.dev
    url_template: "https://github.com/supabase/cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: https://supabase.com
    description: Supabase CLI (Beta)
    license: MIT
nfpms:
  - vendor: Supabase
    description: Supabase CLI
    maintainer: Supabase CLI
    homepage: https://supabase.com
    license: MIT
    formats:
      - apk
      - deb
      - rpm
      - archlinux
