project_name: supabase
before:
  hooks:
    - go mod tidy
builds:
  - id: supabase
    binary: supabase
    ldflags:
      - -X github.com/supabase/cli/cmd.version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
changelog:
  skip: true
brews:
  - tap:
      owner: supabase
      name: homebrew-tap
    commit_author:
      name: Bobbie Soedirgo
      email: bobbie@soedirgo.dev
    homepage: https://supabase.io
    description: Supabase CLI
    license: MIT
scoop:
  bucket:
    owner: supabase
    name: scoop-bucket
  commit_author:
    name: Bobbie Soedirgo
    email: bobbie@soedirgo.dev
  homepage: https://supabase.io
  description: Supabase CLI
  license: MIT
snapcrafts:
  -
    publish: true
    summary: Command Line Interface tool for managing a local Supabase instance.
    confinement: strict 
    grade: stable
