project_name: supabase
before:
  hooks:
    - go mod tidy
builds:
  - id: supabase
    binary: supabase
    ldflags:
      - -X github.com/supabase/cli/cmd.version={{.Version}}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
changelog:
  skip: true
brews:
  - tap:
      owner: supabase
      name: homebrew-tap
    commit_author:
      name: Bobbie Soedirgo
      email: bobbie@soedirgo.dev
    url_template: "https://github.com/supabase/cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: https://supabase.com
    description: Supabase CLI
    license: MIT
    install: |
      bin.install "supabase"
      (bash_completion/"supabase").write `#{bin}/supabase completion bash`
      (fish_completion/"supabase.fish").write `#{bin}/supabase completion fish`
      (zsh_completion/"_supabase").write `#{bin}/supabase completion zsh`
scoop:
  bucket:
    owner: supabase
    name: scoop-bucket
  commit_author:
    name: Bobbie Soedirgo
    email: bobbie@soedirgo.dev
  url_template: "https://github.com/supabase/cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  homepage: https://supabase.com
  description: Supabase CLI
  license: MIT
chocolateys:
  - owners: Supabase
    title: Supabase CLI
    summary: The open source Firebase alternative.
    authors: Supabase CLI
    tags: "Supabase CLI firebase postgres serverless BaaS"
    url_template: "https://github.com/supabase/cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    project_url: https://supabase.com
    icon_rul: https://avatars.githubusercontent.com/u/54469796
    license_url: https://github.com/supabase/cli/blob/main/LICENSE
    package_source_url: https://github.com/supabase/cli
    project_source_url: https://github.com/supabase/cli
    docs_url: https://supabase.com/docs/reference/cli
    bug_tracker_url: https://github.com/supabase/cli/issues
    description: |
      [![Coverage Status](https://coveralls.io/repos/github/supabase/cli/badge.svg?branch=main)](https://coveralls.io/github/supabase/cli?branch=main)

      [Supabase](https://supabase.io) is an open source Firebase alternative. We're building the features of Firebase using enterprise-grade open source tools.

      This repository contains all the functionality for Supabase CLI.

      - [x] Running Supabase locally
      - [x] Managing database migrations
      - [x] Pushing your local changes to production
      - [x] Create and Deploy Supabase Functions
      - [ ] Manage your Supabase Account
      - [x] Manage your Supabase Projects
      - [x] Generating types directly from your database schema
      - [ ] Generating API and validation schemas from your database
    release_notes: "https://github.com/supabase/cli/releases/tag/v{{ .Version }}"
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    source_repo: "https://push.chocolatey.org/"
nfpms:
  - vendor: Supabase
    description: Supabase CLI
    maintainer: Supabase CLI
    homepage: https://supabase.com
    license: MIT
    formats:
      - apk
      - deb
      - rpm
      - archlinux
