project_name: supabase
before:
  hooks:
    - go mod tidy
builds:
  - id: supabase
    binary: supabase
    ldflags:
      - -X github.com/supabase/cli/cmd.version={{.Version}}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
changelog:
  skip: true
brews:
  - tap:
      owner: supabase
      name: homebrew-tap
    commit_author:
      name: Bobbie Soedirgo
      email: bobbie@soedirgo.dev
    homepage: https://supabase.io
    description: Supabase CLI
    license: MIT
    install: |
      bin.install "supabase"
      (bash_completion/"supabase").write `#{bin}/supabase completion bash`
      (fish_completion/"supabase.fish").write `#{bin}/supabase completion fish`
      (zsh_completion/"_supabase").write `#{bin}/supabase completion zsh`
scoop:
  bucket:
    owner: supabase
    name: scoop-bucket
  commit_author:
    name: Bobbie Soedirgo
    email: bobbie@soedirgo.dev
  homepage: https://supabase.io
  description: Supabase CLI
  license: MIT
nfpms:
  - maintainer: Supabase
    description: Supabase CLI
    homepage: https://github.com/supabase/cli
    license: MIT
    formats:
      - apk
      - deb
      - rpm
