monorepo_root = true

[hooks]
# installs the package manager (e.g., pnpm) for the project, if it is not already installed
postinstall = "corepack enable"

[monorepo]
config_roots = [
  "apps/*",
  "packages/*",
]

[settings]
# uses .bun-version and .nvmrc to determine the bun and node versions to use
idiomatic_version_file_enable_tools = ["bun", "node"]

[tools]
# extracts the go version from `apps/cli-go/go.mod`
go = "{{ exec(command=`awk '/^go / {print $2}' apps/cli-go/go.mod`) }}"
golangci-lint = "2"
