monorepo_root = true

min_version = {soft = '2026.6.14'}

[settings]
# uses .bun-version and .nvmrc to determine the bun and node versions to use
idiomatic_version_file_enable_tools = ["bun", "node"]

[tools]
# extracts the go version from `apps/cli-go/go.mod`
go = "{{ exec(command=`awk '/^go / {print $2}' apps/cli-go/go.mod`) }}"
# extracts the golangci-lint version from `apps/cli-go/go.mod`
golangci-lint = "{{ exec(command=`awk '/golangci-lint\\/v2 v/ {print $2}' apps/cli-go/go.mod`) }}"
# just in case it's not already installed, used in the pnpm install step below
jq = "1"
# extracts the pnpm version from `package.json` (in the root)
pnpm = {version = """{{ exec(command=`jq -r '.packageManager | split("@")[1]' package.json`) }}""", depends = ["jq"]}
