packages:
  - "packages/*"
  - "apps/*"
  - "tools/*"

allowBuilds:
  "@swc/core": true
  esbuild: true
  msgpackr-extract: true
  nx: true
  sharp: true

catalog:
  "@effect/atom-react": "4.0.0-beta.70"
  "@effect/platform-bun": "4.0.0-beta.70"
  "@effect/platform-node": "4.0.0-beta.70"
  "@effect/vitest": "^4.0.0-beta.70"
  "@nx/devkit": "^22.7.4"
  "@swc-node/register": "^1.10.9"
  "@swc/core": "^1.15.40"
  "@tsconfig/bun": "^1.0.10"
  "@types/bun": "^1.3.14"
  "@typescript/native-preview": "7.0.0-dev.20260526.1"
  "@vitest/coverage-istanbul": "^4.1.7"
  "effect": "4.0.0-beta.70"
  "knip": "^6.14.2"
  "nx": "^22.7.4"
  "oxfmt": "^0.52.0"
  "oxlint": "^1.67.0"
  "oxlint-tsgolint": "^0.23.0"
  "vitest": "^4.1.7"

supportedArchitectures:
  cpu:
    - current
    - arm64
    - x64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
    - win32
