CREATE TABLE IF NOT EXISTS public.countries (id BIGINT NOT NULL, name TEXT, iso2 TEXT NOT NULL, iso3 TEXT, local_name TEXT, continent continents);
ALTER TABLE public.countries OWNER TO postgres;
ALTER TABLE public.countries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 CACHE 1);
ALTER TABLE ONLY public.countries ADD CONSTRAINT countries_pkey PRIMARY KEY (id);
GRANT ALL ON public.countries TO anon;
GRANT ALL ON public.countries TO authenticated;
GRANT ALL ON public.countries TO service_role;
