#!/usr/bin/env bash
set -euo pipefail

# Explanation of special flags:
#
#   --schema-only     omit data like migration history, pgsodium key, etc.
#   --exclude-schema  omit internal schemas as they are maintained by platform
#   --no-comments     only object owner can set comment, omit to allow restore by non-superuser
#   --extension '*'   prevents event triggers from being dumped, bash escaped with single quote
pg_dump \
    --column-inserts \
    --quote-all-identifier \
    --exclude-schema "$EXCLUDED_SCHEMAS" \
    --extension '*' \
    --no-comments \
    --dbname "$DB_URL" \
| sed 's/CREATE POLICY "cron_job_/-- CREATE POLICY "cron_job_/'

# Reset session config generated by pg_dump
echo "RESET ALL;"
