#!/usr/bin/env bash
set -euo pipefail

# Explanation of pg_dump flags:
#
#   --exclude-schema omit data from internal schemas as they are maintained by platform
#   --schema '*'     include all other schemas by default
pg_dump \
    --data-only \
    --column-inserts \
    --quote-all-identifier \
    --exclude-schema "$EXCLUDED_SCHEMAS" \
    --schema '*' \
    --dbname "$DB_URL"

# Reset session config generated by pg_dump
echo "RESET ALL;"
