#!/usr/bin/env bash
set -euo pipefail

# Explanation of pg_dumpall flags:
#
#   --roles-only     only include create, alter, and grant role statements
pg_dumpall \
    --roles-only \
    --quote-all-identifier \
    --no-role-passwords \
    --no-comments \
    --database "$DB_URL" \
| sed -E "s/^CREATE ROLE \"($RESERVED_ROLES)\"/-- &/" \
| sed -E "s/^ALTER ROLE \"postgres\" WITH NOSUPERUSER/-- &/" \
| sed -E "s/^ALTER ROLE \"authenticator\" SET \"session_preload_libraries\" TO 'supautils'/-- &/"

# Reset session config generated by pg_dump
echo "RESET ALL;"
