// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

const (
	ApiKeyHeaderScopes = "apiKeyHeader.Scopes"
	ApiKeyParamScopes  = "apiKeyParam.Scopes"
	BearerScopes       = "bearer.Scopes"
)

// Defines values for CreateProviderBodyType.
const (
	Saml CreateProviderBodyType = "saml"
)

// CreateFunctionBody defines model for CreateFunctionBody.
type CreateFunctionBody struct {
	Body      string `json:"body"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	VerifyJwt *bool  `json:"verify_jwt,omitempty"`
}

// CreateOrganizationBody defines model for CreateOrganizationBody.
type CreateOrganizationBody = map[string]interface{}

// CreateProjectBody defines model for CreateProjectBody.
type CreateProjectBody = map[string]interface{}

// CreateProviderBody defines model for CreateProviderBody.
type CreateProviderBody struct {
	// Type What type of provider will be created
	Type CreateProviderBodyType `json:"type"`
}

// CreateProviderBodyType What type of provider will be created
type CreateProviderBodyType string

// CreateSecretBody defines model for CreateSecretBody.
type CreateSecretBody = map[string]interface{}

// NetworkRestrictionsRequest defines model for NetworkRestrictionsRequest.
type NetworkRestrictionsRequest = map[string]interface{}

// RemoveNetworkBanRequest defines model for RemoveNetworkBanRequest.
type RemoveNetworkBanRequest = map[string]interface{}

// SslEnforcementRequest defines model for SslEnforcementRequest.
type SslEnforcementRequest = map[string]interface{}

// UpdateCustomHostnameBody defines model for UpdateCustomHostnameBody.
type UpdateCustomHostnameBody = map[string]interface{}

// UpdateFunctionBody defines model for UpdateFunctionBody.
type UpdateFunctionBody struct {
	Body      *string `json:"body,omitempty"`
	Name      *string `json:"name,omitempty"`
	VerifyJwt *bool   `json:"verify_jwt,omitempty"`
}

// UpdatePgsodiumConfigBody defines model for UpdatePgsodiumConfigBody.
type UpdatePgsodiumConfigBody = map[string]interface{}

// UpdatePostgrestConfigBody defines model for UpdatePostgrestConfigBody.
type UpdatePostgrestConfigBody struct {
	MaxRows int `json:"max_rows"`
}

// UpdateProviderBody defines model for UpdateProviderBody.
type UpdateProviderBody = map[string]interface{}

// UpgradeDatabaseBody defines model for UpgradeDatabaseBody.
type UpgradeDatabaseBody = map[string]interface{}

// VanitySubdomainBody defines model for VanitySubdomainBody.
type VanitySubdomainBody = map[string]interface{}

// CreateFunctionParams defines parameters for CreateFunction.
type CreateFunctionParams struct {
	ImportMap *bool   `form:"import_map,omitempty" json:"import_map,omitempty"`
	VerifyJwt *bool   `form:"verify_jwt,omitempty" json:"verify_jwt,omitempty"`
	Name      *string `form:"name,omitempty" json:"name,omitempty"`
	Slug      *string `form:"slug,omitempty" json:"slug,omitempty"`
}

// UpdateFunctionParams defines parameters for UpdateFunction.
type UpdateFunctionParams struct {
	ImportMap *bool   `form:"import_map,omitempty" json:"import_map,omitempty"`
	VerifyJwt *bool   `form:"verify_jwt,omitempty" json:"verify_jwt,omitempty"`
	Name      *string `form:"name,omitempty" json:"name,omitempty"`
}

// DeleteSecretsJSONBody defines parameters for DeleteSecrets.
type DeleteSecretsJSONBody = []string

// CreateSecretsJSONBody defines parameters for CreateSecrets.
type CreateSecretsJSONBody = []CreateSecretBody

// GetTypescriptTypesParams defines parameters for GetTypescriptTypes.
type GetTypescriptTypesParams struct {
	IncludedSchemas *string `form:"included_schemas,omitempty" json:"included_schemas,omitempty"`
}

// CreateOrganizationJSONRequestBody defines body for CreateOrganization for application/json ContentType.
type CreateOrganizationJSONRequestBody = CreateOrganizationBody

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectBody

// CreateProviderJSONRequestBody defines body for CreateProvider for application/json ContentType.
type CreateProviderJSONRequestBody = CreateProviderBody

// UpdateProviderByIdJSONRequestBody defines body for UpdateProviderById for application/json ContentType.
type UpdateProviderByIdJSONRequestBody = UpdateProviderBody

// CreateCustomHostnameConfigJSONRequestBody defines body for CreateCustomHostnameConfig for application/json ContentType.
type CreateCustomHostnameConfigJSONRequestBody = UpdateCustomHostnameBody

// CreateFunctionJSONRequestBody defines body for CreateFunction for application/json ContentType.
type CreateFunctionJSONRequestBody = CreateFunctionBody

// UpdateFunctionJSONRequestBody defines body for UpdateFunction for application/json ContentType.
type UpdateFunctionJSONRequestBody = UpdateFunctionBody

// RemoveNetworkBanJSONRequestBody defines body for RemoveNetworkBan for application/json ContentType.
type RemoveNetworkBanJSONRequestBody = RemoveNetworkBanRequest

// ApplyNetworkRestrictionsJSONRequestBody defines body for ApplyNetworkRestrictions for application/json ContentType.
type ApplyNetworkRestrictionsJSONRequestBody = NetworkRestrictionsRequest

// UpdateConfigJSONRequestBody defines body for UpdateConfig for application/json ContentType.
type UpdateConfigJSONRequestBody = UpdatePgsodiumConfigBody

// UpdatePostgRESTConfigJSONRequestBody defines body for UpdatePostgRESTConfig for application/json ContentType.
type UpdatePostgRESTConfigJSONRequestBody = UpdatePostgrestConfigBody

// DeleteSecretsJSONRequestBody defines body for DeleteSecrets for application/json ContentType.
type DeleteSecretsJSONRequestBody = DeleteSecretsJSONBody

// CreateSecretsJSONRequestBody defines body for CreateSecrets for application/json ContentType.
type CreateSecretsJSONRequestBody = CreateSecretsJSONBody

// UpdateSslEnforcementConfigJSONRequestBody defines body for UpdateSslEnforcementConfig for application/json ContentType.
type UpdateSslEnforcementConfigJSONRequestBody = SslEnforcementRequest

// UpgradeProjectJSONRequestBody defines body for UpgradeProject for application/json ContentType.
type UpgradeProjectJSONRequestBody = UpgradeDatabaseBody

// ActivateVanitySubdomainPleaseJSONRequestBody defines body for ActivateVanitySubdomainPlease for application/json ContentType.
type ActivateVanitySubdomainPleaseJSONRequestBody = VanitySubdomainBody

// CheckVanitySubdomainAvailabilityJSONRequestBody defines body for CheckVanitySubdomainAvailability for application/json ContentType.
type CheckVanitySubdomainAvailabilityJSONRequestBody = VanitySubdomainBody
