-- Generated by Supabase CLI


/*   
 * data  
*/
alter table "public"."users" add column 
"data"                
    jsonb -- type
    default  -- default
;
comment on column "public"."users"."data" is 
"";

/*   
 * first_name  
*/
alter table "public"."users" add column 
"first_name"                
    text -- type
    default  -- default
;
comment on column "public"."users"."first_name" is 
"";

/*   
 * id  
*/
alter table "public"."users" add column 
"id"                
    bigint -- type
    default  -- default
;
comment on column "public"."users"."id" is 
"";

/*   
 * inserted_at  
*/
alter table "public"."users" add column 
"inserted_at"                
    timestamp without time zone -- type
    default timezone(&#39;utc&#39;::text, now()) -- default
;
comment on column "public"."users"."inserted_at" is 
"";

/*   
 * last_name  
*/
alter table "public"."users" add column 
"last_name"                
    text -- type
    default  -- default
;
comment on column "public"."users"."last_name" is 
"";

/*   
 * updated_at  
*/
alter table "public"."users" add column 
"updated_at"                
    timestamp without time zone -- type
    default timezone(&#39;utc&#39;::text, now()) -- default
;
comment on column "public"."users"."updated_at" is 
"";

/*   
 * username  
*/
alter table "public"."users" add column 
"username"                
    text -- type
    default  -- default
;
comment on column "public"."users"."username" is 
"";



