import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { afterAll, beforeAll, expect, test } from "vitest";

import { describe } from "vitest";
import {
  makeTempLegacyStackProject,
  overrideStackPorts,
  requireCliSuccess,
  runSupabase,
} from "../../../../../../../tests/helpers/cli.ts";

const CLI_COMMAND_TIMEOUT_MS = 60_000;
const STACK_START_TIMEOUT_MS = 280_000;
const CLEANUP_TIMEOUT_MS = 120_000;
const LIFECYCLE_MARGIN_MS = 30_000;
const CLEANUP_HOOK_TIMEOUT_MS = CLEANUP_TIMEOUT_MS + LIFECYCLE_MARGIN_MS;
const SCENARIO_COMMAND_TIMEOUT_MS = 280_000;
const BEFORE_ALL_TIMEOUT_MS = CLI_COMMAND_TIMEOUT_MS + STACK_START_TIMEOUT_MS + LIFECYCLE_MARGIN_MS;
const SCENARIO_TIMEOUT_MS = 900_000;
const NEXT_ENV = { SUPABASE_USE_PG_DELTA_NEXT: "true" };

const initialDesiredSchema = `create type public.account_state as enum ('pending', 'active');

create table public.disposable_note (
  id bigint generated by default as identity primary key,
  body text not null
);

create view public.auth_user_emails as
select id, email
from auth.users;
`;

function commandFailure(result: { stdout: string; stderr: string }): string {
  return `stdout:\n${result.stdout}\nstderr:\n${result.stderr}`;
}

function migrationFiles(projectDir: string): ReadonlyArray<string> {
  const migrationsDir = path.join(projectDir, "supabase", "migrations");
  return existsSync(migrationsDir)
    ? readdirSync(migrationsDir)
        .filter((file) => file.endsWith(".sql"))
        .sort()
    : [];
}

describe("db schema declarative sync (e2e)", () => {
  let project: Awaited<ReturnType<typeof makeTempLegacyStackProject>> | undefined;

  beforeAll(async () => {
    project = await makeTempLegacyStackProject("sb-pgdelta-next-e2e-");
    const projectDir = project.dir;

    const init = await runSupabase(["init"], {
      entrypoint: "legacy",
      cwd: projectDir,
      exitTimeoutMs: CLI_COMMAND_TIMEOUT_MS,
    });
    requireCliSuccess(init, "init setup");
    await overrideStackPorts(projectDir);

    const configPath = path.join(projectDir, "supabase", "config.toml");
    const config = readFileSync(configPath, "utf8");
    if (!config.includes("[experimental.pgdelta]\nenabled = true")) {
      throw new Error("init setup did not enable experimental pg-delta in config.toml");
    }
    writeFileSync(
      configPath,
      config.replace(
        '# declarative_schema_path = "./schemas"',
        'declarative_schema_path = "./schemas"',
      ),
    );

    const schemasDir = path.join(projectDir, "supabase", "schemas");
    mkdirSync(schemasDir, { recursive: true });
    writeFileSync(path.join(schemasDir, "public.sql"), initialDesiredSchema);
    const extensionsDir = path.join(schemasDir, "cluster", "extensions");
    mkdirSync(extensionsDir, { recursive: true });
    for (const extension of ["pg_net", "pgcrypto", "uuid-ossp"]) {
      writeFileSync(
        path.join(extensionsDir, `${extension}.sql`),
        `CREATE EXTENSION IF NOT EXISTS "${extension}" WITH SCHEMA "extensions";\n`,
      );
    }
    // Both install into a fixed schema, so no `WITH SCHEMA` clause.
    for (const extension of ["pg_cron", "pgmq"]) {
      writeFileSync(
        path.join(extensionsDir, `${extension}.sql`),
        `CREATE EXTENSION IF NOT EXISTS "${extension}";\n`,
      );
    }

    const start = await runSupabase(
      [
        "start",
        "--exclude",
        "studio",
        "--exclude",
        "logflare",
        "--exclude",
        "vector",
        "--exclude",
        "gotrue",
        "--exclude",
        "realtime",
        "--exclude",
        "storage-api",
      ],
      { entrypoint: "legacy", cwd: projectDir, exitTimeoutMs: STACK_START_TIMEOUT_MS },
    );
    requireCliSuccess(start, "start setup");
  }, BEFORE_ALL_TIMEOUT_MS);

  afterAll(async () => {
    await project?.cleanup().catch(() => undefined);
    project = undefined;
  }, CLEANUP_HOOK_TIMEOUT_MS);

  test(
    "applies a representative declarative schema and converges",
    { timeout: SCENARIO_TIMEOUT_MS },
    async () => {
      const projectDir = project?.dir;
      if (projectDir === undefined) throw new Error("declarative sync project was not initialized");

      const sync = await runSupabase(
        [
          "db",
          "schema",
          "declarative",
          "sync",
          "--no-apply",
          "--name",
          "initial_declarative",
          "--experimental",
        ],
        {
          entrypoint: "legacy",
          cwd: projectDir,
          env: NEXT_ENV,
          exitTimeoutMs: SCENARIO_COMMAND_TIMEOUT_MS,
        },
      );
      expect(sync.exitCode, commandFailure(sync)).toBe(0);

      const migrations = migrationFiles(projectDir);
      expect(migrations.length).toBeGreaterThan(0);
      const sql = migrations
        .map((file) => readFileSync(path.join(projectDir, "supabase", "migrations", file), "utf8"))
        .join("\n");
      expect(sql).toContain("account_state");
      expect(sql).toContain("disposable_note");
      expect(sql).toContain("auth_user_emails");
      expect(sql).toContain("auth.users");
      expect(sql).not.toMatch(
        /CREATE\s+(?:SCHEMA|TABLE)\s+(?:IF\s+NOT\s+EXISTS\s+)?["']?(?:auth|storage|realtime)["']?/iu,
      );

      const reset = await runSupabase(["db", "reset", "--local", "--no-seed"], {
        entrypoint: "legacy",
        cwd: projectDir,
        exitTimeoutMs: SCENARIO_COMMAND_TIMEOUT_MS,
      });
      requireCliSuccess(reset, "db reset setup");

      const converged = await runSupabase(
        ["db", "schema", "declarative", "sync", "--no-apply", "--experimental"],
        {
          entrypoint: "legacy",
          cwd: projectDir,
          env: NEXT_ENV,
          exitTimeoutMs: SCENARIO_COMMAND_TIMEOUT_MS,
        },
      );
      expect(converged.exitCode, commandFailure(converged)).toBe(0);
      expect(`${converged.stdout}${converged.stderr}`).toContain("No schema changes found");
    },
  );

  test(
    "renames a cron job and drops a pgmq queue declared in the tree",
    { timeout: SCENARIO_TIMEOUT_MS },
    async () => {
      const projectDir = project?.dir;
      if (projectDir === undefined) throw new Error("declarative sync project was not initialized");
      const jobsPath = path.join(projectDir, "supabase", "schemas", "jobs.sql");
      const sync = (name: string) =>
        runSupabase(
          ["db", "schema", "declarative", "sync", "--no-apply", "--name", name, "--experimental"],
          {
            entrypoint: "legacy",
            cwd: projectDir,
            env: NEXT_ENV,
            exitTimeoutMs: SCENARIO_COMMAND_TIMEOUT_MS,
          },
        );
      // A next-engine plan may span several ordered migration files; read every
      // file a sync added rather than only the last one.
      const syncAndReadSql = async (name: string) => {
        const before = new Set(migrationFiles(projectDir));
        const result = await sync(name);
        expect(result.exitCode, commandFailure(result)).toBe(0);
        const added = migrationFiles(projectDir).filter((file) => !before.has(file));
        expect(added.length, "sync did not write a migration").toBeGreaterThan(0);
        return {
          result,
          sql: added
            .map((file) =>
              readFileSync(path.join(projectDir, "supabase", "migrations", file), "utf8"),
            )
            .join("\n"),
        };
      };

      writeFileSync(
        jobsPath,
        [
          "select cron.schedule('nightly_cleanup', '0 3 * * *', $$delete from public.disposable_note$$);",
          "select pgmq.create('emails');",
          "",
        ].join("\n"),
      );
      const added = await syncAndReadSql("add_jobs");
      expect(added.sql).toContain("cron.schedule('nightly_cleanup'");
      expect(added.sql).toContain("pgmq.create('emails')");

      // Rename the job and drop the queue: previously refused as a legacy export.
      writeFileSync(
        jobsPath,
        "select cron.schedule('weekly_cleanup', '0 3 * * 0', $$delete from public.disposable_note$$);\n",
      );
      const removed = await syncAndReadSql("rename_job_drop_queue");
      expect(`${removed.result.stdout}${removed.result.stderr}`).not.toContain(
        "legacy pg-delta export",
      );
      expect(removed.sql).toContain("cron.unschedule('nightly_cleanup')");
      expect(removed.sql).toContain("cron.schedule('weekly_cleanup'");
      expect(removed.sql).toContain("pgmq.drop_queue('emails')");
    },
  );
});
