import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterAll, beforeAll, expect, test } from "vitest";

import { describeDockerLive, runSupabaseLive } from "../../../../../tests/helpers/live.ts";

const COMMAND_TIMEOUT_MS = 280_000;
const SCENARIO_TIMEOUT_MS = 900_000;
const NEXT_ENV = { SUPABASE_USE_PG_DELTA_NEXT: "true" };

const initialDesiredSchema = `create type public.account_state as enum ('pending', 'active');

create table public.disposable_note (
  id bigint generated by default as identity primary key,
  body text not null
);

create view public.auth_user_emails as
select id, email
from auth.users;
`;

function commandFailure(result: { stdout: string; stderr: string }): string {
  return `stdout:\n${result.stdout}\nstderr:\n${result.stderr}`;
}

function migrationFiles(projectDir: string): ReadonlyArray<string> {
  const migrationsDir = path.join(projectDir, "supabase", "migrations");
  return existsSync(migrationsDir)
    ? readdirSync(migrationsDir)
        .filter((file) => file.endsWith(".sql"))
        .sort()
    : [];
}

describeDockerLive("pg-delta next local convergence (live)", () => {
  let projectDir = "";

  beforeAll(async () => {
    projectDir = await mkdtemp(path.join(tmpdir(), "sb-pgdelta-next-live-"));

    const init = await runSupabaseLive(["init"], {
      cwd: projectDir,
      exitTimeoutMs: COMMAND_TIMEOUT_MS,
    });
    expect(init.exitCode, commandFailure(init)).toBe(0);

    const configPath = path.join(projectDir, "supabase", "config.toml");
    const config = readFileSync(configPath, "utf8");
    expect(config).toContain("schema_paths = []");
    expect(config).toContain("[experimental.pgdelta]\nenabled = true");
    writeFileSync(
      configPath,
      config
        .replace("schema_paths = []", 'schema_paths = ["./schemas/*.sql"]')
        .replace(
          '# declarative_schema_path = "./database"',
          'declarative_schema_path = "./schemas"',
        ),
    );

    const schemasDir = path.join(projectDir, "supabase", "schemas");
    mkdirSync(schemasDir, { recursive: true });
    writeFileSync(path.join(schemasDir, "public.sql"), initialDesiredSchema);

    const start = await runSupabaseLive(
      [
        "start",
        "--exclude",
        "studio",
        "--exclude",
        "logflare",
        "--exclude",
        "vector",
        "--exclude",
        "gotrue",
        "--exclude",
        "realtime",
        "--exclude",
        "storage-api",
      ],
      { cwd: projectDir, exitTimeoutMs: COMMAND_TIMEOUT_MS },
    );
    expect(start.exitCode, commandFailure(start)).toBe(0);
  }, COMMAND_TIMEOUT_MS);

  afterAll(async () => {
    if (projectDir.length === 0) return;
    await runSupabaseLive(["stop", "--no-backup"], {
      cwd: projectDir,
      exitTimeoutMs: COMMAND_TIMEOUT_MS,
    }).catch(() => undefined);
    await rm(projectDir, { recursive: true, force: true }).catch(() => undefined);
  }, COMMAND_TIMEOUT_MS);

  test(
    "applies a representative declarative schema and converges",
    { timeout: SCENARIO_TIMEOUT_MS },
    async () => {
      expect(migrationFiles(projectDir)).toEqual([]);

      const diff = await runSupabaseLive(
        ["db", "diff", "--local", "--use-pg-delta", "-f", "initial_declarative"],
        { cwd: projectDir, env: NEXT_ENV, exitTimeoutMs: COMMAND_TIMEOUT_MS },
      );
      expect(diff.exitCode, commandFailure(diff)).toBe(0);

      const migrations = migrationFiles(projectDir);
      expect(migrations.length).toBeGreaterThan(0);
      const sql = migrations
        .map((file) => readFileSync(path.join(projectDir, "supabase", "migrations", file), "utf8"))
        .join("\n");
      expect(sql).toContain("account_state");
      expect(sql).toContain("disposable_note");
      expect(sql).toContain("auth_user_emails");
      expect(sql).toContain("auth.users");
      expect(sql).not.toMatch(
        /CREATE\s+(?:SCHEMA|TABLE)\s+(?:IF\s+NOT\s+EXISTS\s+)?["']?(?:auth|storage|realtime)["']?/iu,
      );

      const reset = await runSupabaseLive(["db", "reset", "--local", "--no-seed"], {
        cwd: projectDir,
        exitTimeoutMs: COMMAND_TIMEOUT_MS,
      });
      expect(reset.exitCode, commandFailure(reset)).toBe(0);

      const converged = await runSupabaseLive(["db", "diff", "--local", "--use-pg-delta"], {
        cwd: projectDir,
        env: NEXT_ENV,
        exitTimeoutMs: COMMAND_TIMEOUT_MS,
      });
      expect(converged.exitCode, commandFailure(converged)).toBe(0);
      expect(converged.stderr).toContain("No schema changes found");
    },
  );
});
