import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  renameSync,
  writeFileSync,
} from "node:fs";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterAll, beforeAll, expect, test } from "vitest";

import { describeDockerLive, runSupabaseLive } from "../../../../../tests/helpers/live.ts";

const COMMAND_TIMEOUT_MS = 280_000;
const SCENARIO_TIMEOUT_MS = 900_000;
const NEXT_ENV = {
  PGDELTA_DEBUG: "1",
  SUPABASE_USE_PG_DELTA_NEXT: "true",
};

const initialDesiredSchema = `create type public.account_state as enum ('pending', 'active');

create table public.disposable_note (
  id bigint generated by default as identity primary key,
  body text not null
);

create view public.auth_user_emails as
select id, email
from auth.users;
`;

const editedDesiredSchema = `create type public.account_state as enum ('pending', 'review', 'active');

create view public.auth_user_emails as
select id, email
from auth.users;

create table public.review_queue (
  id bigint primary key,
  state public.account_state not null default 'review'
);
`;

function commandFailure(result: { stdout: string; stderr: string }): string {
  return `stdout:\n${result.stdout}\nstderr:\n${result.stderr}`;
}

function migrationFiles(projectDir: string): ReadonlyArray<string> {
  const migrationsDir = path.join(projectDir, "supabase", "migrations");
  return existsSync(migrationsDir)
    ? readdirSync(migrationsDir)
        .filter((file) => file.endsWith(".sql"))
        .sort()
    : [];
}

function debugBundleDirectories(projectDir: string): ReadonlyArray<string> {
  const debugDir = path.join(projectDir, "supabase", ".temp", "pgdelta", "v2", "debug");
  if (!existsSync(debugDir)) return [];
  return readdirSync(debugDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => path.join(debugDir, entry.name))
    .sort();
}

function requireDebugBundle(projectDir: string, operation: "declarativePlan" | "diff"): string {
  const bundle = debugBundleDirectories(projectDir)
    .filter((dir) => path.basename(dir).endsWith(`-${operation}`))
    .at(-1);
  expect(bundle, `missing ${operation} debug bundle`).toBeDefined();
  if (bundle === undefined) throw new Error(`missing ${operation} debug bundle`);
  return bundle;
}

function assertJsonFile(file: string): unknown {
  expect(existsSync(file), `missing ${file}`).toBe(true);
  return JSON.parse(readFileSync(file, "utf8"));
}

function localDatabaseUrl(config: string): string {
  const dbSection = config.match(/\[db\][\s\S]*?\nport\s*=\s*(\d+)/u);
  expect(dbSection?.[1], "db.port missing from generated config.toml").toBeDefined();
  return `postgresql://postgres:postgres@127.0.0.1:${dbSection?.[1]}/postgres?sslmode=disable`;
}

describeDockerLive("pg-delta next local convergence (live)", () => {
  let projectDir = "";
  let desiredSchemaPath = "";
  let databaseUrl = "";

  beforeAll(async () => {
    projectDir = await mkdtemp(path.join(tmpdir(), "sb-pgdelta-next-live-"));

    const init = await runSupabaseLive(["init"], {
      cwd: projectDir,
      exitTimeoutMs: COMMAND_TIMEOUT_MS,
    });
    expect(init.exitCode, commandFailure(init)).toBe(0);

    const configPath = path.join(projectDir, "supabase", "config.toml");
    const config = readFileSync(configPath, "utf8");
    expect(config).toContain("schema_paths = []");
    expect(config).toContain("[experimental.pgdelta]\nenabled = true");
    writeFileSync(
      configPath,
      config
        .replace("schema_paths = []", 'schema_paths = ["./schemas/*.sql"]')
        .replace(
          '# declarative_schema_path = "./database"',
          'declarative_schema_path = "./schemas"',
        ),
    );
    databaseUrl = localDatabaseUrl(config);

    const schemasDir = path.join(projectDir, "supabase", "schemas");
    mkdirSync(schemasDir, { recursive: true });
    desiredSchemaPath = path.join(schemasDir, "public.sql");
    writeFileSync(desiredSchemaPath, initialDesiredSchema);

    const start = await runSupabaseLive(
      [
        "start",
        "--exclude",
        "studio",
        "--exclude",
        "logflare",
        "--exclude",
        "vector",
        "--exclude",
        "gotrue",
        "--exclude",
        "realtime",
        "--exclude",
        "storage-api",
      ],
      { cwd: projectDir, exitTimeoutMs: COMMAND_TIMEOUT_MS },
    );
    expect(start.exitCode, commandFailure(start)).toBe(0);
  }, COMMAND_TIMEOUT_MS);

  afterAll(async () => {
    if (projectDir.length === 0) return;
    await runSupabaseLive(["stop", "--no-backup"], {
      cwd: projectDir,
      exitTimeoutMs: COMMAND_TIMEOUT_MS,
    }).catch(() => undefined);
    await rm(projectDir, { recursive: true, force: true }).catch(() => undefined);
  }, COMMAND_TIMEOUT_MS);

  test(
    "converges declarative state across empty, destructive, enum, URL, and migrations refs",
    { timeout: SCENARIO_TIMEOUT_MS },
    async () => {
      expect(migrationFiles(projectDir)).toEqual([]);

      const initialDiff = await runSupabaseLive(
        ["db", "diff", "--local", "--use-pg-delta", "-f", "initial_declarative"],
        { cwd: projectDir, env: NEXT_ENV, exitTimeoutMs: COMMAND_TIMEOUT_MS },
      );
      expect(initialDiff.exitCode, commandFailure(initialDiff)).toBe(0);

      const initialMigrations = migrationFiles(projectDir);
      expect(initialMigrations.length).toBeGreaterThan(0);
      const initialSql = initialMigrations
        .map((file) => readFileSync(path.join(projectDir, "supabase", "migrations", file), "utf8"))
        .join("\n");
      expect(initialSql).toContain("account_state");
      expect(initialSql).toContain("disposable_note");
      expect(initialSql).toContain("auth_user_emails");
      expect(initialSql).toContain("auth.users");
      expect(initialSql).not.toMatch(
        /CREATE\s+(?:SCHEMA|TABLE)\s+(?:IF\s+NOT\s+EXISTS\s+)?["']?(?:auth|storage|realtime)["']?/iu,
      );

      const declarativeBundle = requireDebugBundle(projectDir, "declarativePlan");
      expect(assertJsonFile(path.join(declarativeBundle, "metadata.json"))).toMatchObject({
        version: 1,
        generation: "v2",
        implementation: "next",
        operation: "declarativePlan",
        cacheReusable: false,
        files: ["diagnostics.json", "plan.json"],
      });
      assertJsonFile(path.join(declarativeBundle, "plan.json"));
      expect(Array.isArray(assertJsonFile(path.join(declarativeBundle, "diagnostics.json")))).toBe(
        true,
      );

      const firstReset = await runSupabaseLive(["db", "reset", "--local", "--no-seed"], {
        cwd: projectDir,
        exitTimeoutMs: COMMAND_TIMEOUT_MS,
      });
      expect(firstReset.exitCode, commandFailure(firstReset)).toBe(0);

      const emptyAfterInitial = await runSupabaseLive(["db", "diff", "--local", "--use-pg-delta"], {
        cwd: projectDir,
        env: { SUPABASE_USE_PG_DELTA_NEXT: "true" },
        exitTimeoutMs: COMMAND_TIMEOUT_MS,
      });
      expect(emptyAfterInitial.exitCode, commandFailure(emptyAfterInitial)).toBe(0);
      expect(emptyAfterInitial.stderr).toContain("No schema changes found");

      writeFileSync(desiredSchemaPath, editedDesiredSchema);
      const beforeEdit = new Set(migrationFiles(projectDir));
      const editedDiff = await runSupabaseLive(
        ["db", "diff", "--local", "--use-pg-delta", "-f", "enum_and_drop"],
        {
          cwd: projectDir,
          env: { SUPABASE_USE_PG_DELTA_NEXT: "true" },
          exitTimeoutMs: COMMAND_TIMEOUT_MS,
        },
      );
      expect(editedDiff.exitCode, commandFailure(editedDiff)).toBe(0);
      expect(editedDiff.stderr).toContain("Found drop statements in schema diff");

      const editedMigrations = migrationFiles(projectDir).filter((file) => !beforeEdit.has(file));
      expect(editedMigrations.length).toBeGreaterThan(1);
      const editedMigrationSql = editedMigrations.map((file) =>
        readFileSync(path.join(projectDir, "supabase", "migrations", file), "utf8"),
      );
      const editedSql = editedMigrationSql.join("\n");
      expect(editedSql).toMatch(/ALTER\s+TYPE[\s\S]*account_state[\s\S]*ADD\s+VALUE/iu);
      expect(editedSql).toMatch(/DROP\s+TABLE[\s\S]*disposable_note/iu);
      expect(editedSql).toContain("review_queue");

      const enumPush = await runSupabaseLive(["db", "push", "--local"], {
        cwd: projectDir,
        env: { SUPABASE_YES: "true" },
        exitTimeoutMs: COMMAND_TIMEOUT_MS,
      });
      expect(enumPush.exitCode, commandFailure(enumPush)).toBe(0);

      const emptyAfterEdit = await runSupabaseLive(["db", "diff", "--local", "--use-pg-delta"], {
        cwd: projectDir,
        env: { SUPABASE_USE_PG_DELTA_NEXT: "true" },
        exitTimeoutMs: COMMAND_TIMEOUT_MS,
      });
      expect(emptyAfterEdit.exitCode, commandFailure(emptyAfterEdit)).toBe(0);
      expect(emptyAfterEdit.stderr).toContain("No schema changes found");

      const explicit = await runSupabaseLive(
        ["db", "diff", "--from", "migrations", "--to", databaseUrl],
        { cwd: projectDir, env: NEXT_ENV, exitTimeoutMs: COMMAND_TIMEOUT_MS },
      );
      expect(explicit.exitCode, commandFailure(explicit)).toBe(0);
      expect(explicit.stdout.trim()).toBe("");

      const diffBundle = requireDebugBundle(projectDir, "diff");
      expect(assertJsonFile(path.join(diffBundle, "metadata.json"))).toMatchObject({
        version: 1,
        generation: "v2",
        implementation: "next",
        operation: "diff",
        cacheReusable: false,
        files: ["desired-snapshot.json", "diagnostics.json", "plan.json", "source-snapshot.json"],
      });
      const sourceSnapshot = readFileSync(path.join(diffBundle, "source-snapshot.json"), "utf8");
      const desiredSnapshot = readFileSync(path.join(diffBundle, "desired-snapshot.json"), "utf8");
      expect(sourceSnapshot).toContain("account_state");
      expect(desiredSnapshot).toContain("account_state");
      JSON.parse(sourceSnapshot);
      JSON.parse(desiredSnapshot);
      assertJsonFile(path.join(diffBundle, "plan.json"));
      expect(Array.isArray(assertJsonFile(path.join(diffBundle, "diagnostics.json")))).toBe(true);

      const generated = await runSupabaseLive(
        ["db", "schema", "declarative", "generate", "--local", "--overwrite"],
        {
          cwd: projectDir,
          env: { SUPABASE_USE_PG_DELTA_NEXT: "true" },
          exitTimeoutMs: COMMAND_TIMEOUT_MS,
        },
      );
      expect(generated.exitCode, commandFailure(generated)).toBe(0);

      const exportedFiles = readdirSync(path.join(projectDir, "supabase", "schemas"), {
        recursive: true,
      })
        .filter((entry): entry is string => typeof entry === "string" && entry.endsWith(".sql"))
        .map((entry) => path.join(projectDir, "supabase", "schemas", entry))
        .sort();
      expect(exportedFiles.length).toBeGreaterThan(0);
      expect(existsSync(path.join(projectDir, "supabase", "schemas", ".pgdelta-export.json"))).toBe(
        true,
      );

      const migrationsBeforeGeneratedSync = migrationFiles(projectDir);
      const emptyGeneratedSync = await runSupabaseLive(
        ["db", "schema", "declarative", "sync", "--no-apply"],
        {
          cwd: projectDir,
          env: { SUPABASE_USE_PG_DELTA_NEXT: "true" },
          exitTimeoutMs: COMMAND_TIMEOUT_MS,
        },
      );
      expect(emptyGeneratedSync.exitCode, commandFailure(emptyGeneratedSync)).toBe(0);
      expect(emptyGeneratedSync.stderr).toContain("No schema changes found");
      expect(migrationFiles(projectDir)).toEqual(migrationsBeforeGeneratedSync);

      const editedExport = exportedFiles[0];
      expect(editedExport).toBeDefined();
      if (editedExport === undefined) throw new Error("declarative export produced no SQL files");
      writeFileSync(
        editedExport,
        `${readFileSync(editedExport, "utf8")}\ncreate table public.phase6_synced (id bigint primary key);\n`,
      );

      const migrationsBeforeApplySync = new Set(migrationFiles(projectDir));
      const appliedSync = await runSupabaseLive(
        ["db", "schema", "declarative", "sync", "--apply", "--name", "phase6_sync"],
        {
          cwd: projectDir,
          env: { SUPABASE_USE_PG_DELTA_NEXT: "true" },
          exitTimeoutMs: COMMAND_TIMEOUT_MS,
        },
      );
      expect(appliedSync.exitCode, commandFailure(appliedSync)).toBe(0);
      expect(appliedSync.stderr).toContain("Migration applied successfully");
      const appliedSyncMigrations = migrationFiles(projectDir).filter(
        (file) => !migrationsBeforeApplySync.has(file),
      );
      expect(appliedSyncMigrations.length).toBeGreaterThan(0);
      expect(
        appliedSyncMigrations
          .map((file) =>
            readFileSync(path.join(projectDir, "supabase", "migrations", file), "utf8"),
          )
          .join("\n"),
      ).toContain("phase6_synced");

      const emptyAppliedSync = await runSupabaseLive(
        ["db", "schema", "declarative", "sync", "--no-apply"],
        {
          cwd: projectDir,
          env: { SUPABASE_USE_PG_DELTA_NEXT: "true" },
          exitTimeoutMs: COMMAND_TIMEOUT_MS,
        },
      );
      expect(emptyAppliedSync.exitCode, commandFailure(emptyAppliedSync)).toBe(0);
      expect(emptyAppliedSync.stderr).toContain("No schema changes found");

      const dbOnlyChange = await runSupabaseLive(
        ["db", "query", "--local", "create table public.phase6_pulled (id bigint primary key)"],
        { cwd: projectDir, exitTimeoutMs: COMMAND_TIMEOUT_MS },
      );
      expect(dbOnlyChange.exitCode, commandFailure(dbOnlyChange)).toBe(0);

      const configPath = path.join(projectDir, "supabase", "config.toml");
      const pullConfig = readFileSync(configPath, "utf8")
        .replace('schema_paths = ["./schemas/*.sql"]', "schema_paths = []")
        .replace('declarative_schema_path = "./schemas"', 'declarative_schema_path = "./database"');
      writeFileSync(configPath, pullConfig);
      renameSync(
        path.join(projectDir, "supabase", "schemas"),
        path.join(projectDir, "supabase", ".phase6-exported-schemas"),
      );

      const migrationsBeforePull = new Set(migrationFiles(projectDir));
      const pulled = await runSupabaseLive(
        ["db", "pull", "phase6_pull", "--db-url", databaseUrl, "--diff-engine", "pg-delta"],
        {
          cwd: projectDir,
          env: { SUPABASE_USE_PG_DELTA_NEXT: "true", SUPABASE_YES: "true" },
          exitTimeoutMs: COMMAND_TIMEOUT_MS,
        },
      );
      expect(pulled.exitCode, commandFailure(pulled)).toBe(0);
      const pulledMigrations = migrationFiles(projectDir).filter(
        (file) => !migrationsBeforePull.has(file),
      );
      expect(pulledMigrations.length).toBeGreaterThan(0);
      expect(
        pulledMigrations
          .map((file) =>
            readFileSync(path.join(projectDir, "supabase", "migrations", file), "utf8"),
          )
          .join("\n"),
      ).toContain("phase6_pulled");

      const removePulledTable = await runSupabaseLive(
        ["db", "query", "--local", "drop table public.phase6_pulled"],
        {
          cwd: projectDir,
          exitTimeoutMs: COMMAND_TIMEOUT_MS,
        },
      );
      expect(removePulledTable.exitCode, commandFailure(removePulledTable)).toBe(0);

      const pulledVersion = pulledMigrations[0]?.split("_", 1)[0];
      expect(pulledVersion).toMatch(/^\d{14}$/u);
      if (pulledVersion === undefined) throw new Error("db pull produced no migration version");
      const markPulledReverted = await runSupabaseLive(
        ["migration", "repair", "--local", "--status", "reverted", pulledVersion],
        {
          cwd: projectDir,
          exitTimeoutMs: COMMAND_TIMEOUT_MS,
        },
      );
      expect(markPulledReverted.exitCode, commandFailure(markPulledReverted)).toBe(0);

      const pullPush = await runSupabaseLive(["db", "push", "--local"], {
        cwd: projectDir,
        env: { SUPABASE_YES: "true" },
        exitTimeoutMs: COMMAND_TIMEOUT_MS,
      });
      expect(pullPush.exitCode, commandFailure(pullPush)).toBe(0);

      const emptyPull = await runSupabaseLive(
        ["db", "pull", "phase6_pull_empty", "--db-url", databaseUrl, "--diff-engine", "pg-delta"],
        {
          cwd: projectDir,
          env: { SUPABASE_USE_PG_DELTA_NEXT: "true", SUPABASE_YES: "true" },
          exitTimeoutMs: COMMAND_TIMEOUT_MS,
        },
      );
      expect(emptyPull.exitCode, commandFailure(emptyPull)).toBe(1);
      expect(emptyPull.stderr).toContain("No schema changes found");
    },
  );

  test(
    "keeps the legacy edge-runtime implementation available behind the opt-out",
    { timeout: SCENARIO_TIMEOUT_MS },
    async (context) => {
      const legacy = await runSupabaseLive(
        ["db", "diff", "--from", "migrations", "--to", databaseUrl],
        {
          cwd: projectDir,
          env: { SUPABASE_USE_PG_DELTA_NEXT: "false" },
          exitTimeoutMs: COMMAND_TIMEOUT_MS,
        },
      );
      const output = `${legacy.stdout}\n${legacy.stderr}`;
      if (
        legacy.exitCode !== 0 &&
        /(?:No such image|manifest unknown|pull access denied|edge-runtime: (?:not found|command not found))/iu.test(
          output,
        )
      ) {
        context.skip("legacy edge-runtime image is concretely unavailable on this Docker host");
      }
      expect(legacy.exitCode, commandFailure(legacy)).toBe(0);
    },
  );
});
