import type { LegacyPgDeltaImplementation } from "../../../../shared/legacy-pgdelta-next-flag.ts";
import type { LegacyPgDeltaRemovalSummary } from "../../shared/legacy-pgdelta-engine.service.ts";

/**
 * Pure control-flow helpers ported 1:1 from
 * `apps/cli-go/cmd/db_schema_declarative.go`. Kept free of Effect/services so
 * the precedence rules are unit-testable in isolation; the handlers run the
 * actual TTY prompt for the `"prompt"` decision.
 */

/**
 * Resolves the migration name. The explicit `--name` wins over `--file`
 * (default `declarative_sync`). Mirrors Go's `resolveDeclarativeMigrationName`
 * (`:99-104`).
 */
export function legacyResolveDeclarativeMigrationName(name: string, file: string): string {
  return name.length > 0 ? name : file;
}

/** Whether sync applies the generated migration, prompts, or skips. */
export type LegacyDeclarativeApplyDecision = "apply" | "skip" | "prompt";

/**
 * Decides whether to apply the generated migration to the local database.
 * Precedence (Go's `resolveDeclarativeSyncShouldApply`, `:106-124`):
 * `--no-apply` > `--apply` > global `--yes` > TTY prompt > non-TTY default (skip).
 */
export function legacyResolveDeclarativeSyncApplyDecision(opts: {
  readonly apply: boolean;
  readonly noApply: boolean;
  readonly yes: boolean;
  readonly tty: boolean;
}): LegacyDeclarativeApplyDecision {
  if (opts.noApply) return "skip";
  if (opts.apply) return "apply";
  if (opts.yes) return "apply";
  if (opts.tty) return "prompt";
  return "skip";
}

/**
 * Warns when pg-delta next sees semantic removals that a manifest-less,
 * potentially legacy-authored declarative tree may simply have omitted.
 */
export function legacyDeclarativeCompatibilityWarning(opts: {
  readonly implementation: LegacyPgDeltaImplementation;
  readonly manifestPresent: boolean;
  readonly removals: LegacyPgDeltaRemovalSummary;
}): string | undefined {
  if (opts.implementation !== "next" || opts.manifestPresent) return undefined;
  const { extensions, extensionIntents } = opts.removals;
  if (extensions.length === 0 && extensionIntents.length === 0) return undefined;

  const cronJobs = extensionIntents
    .filter((intent) => intent.extension === "pg_cron" && intent.intentKind === "job")
    .map((intent) => intent.key);
  const otherIntents = extensionIntents.filter(
    (intent) => intent.extension !== "pg_cron" || intent.intentKind !== "job",
  );
  const detected = [
    ...(extensions.length > 0 ? [`Extensions: ${extensions.join(", ")}`] : []),
    ...(cronJobs.length > 0 ? [`pg_cron jobs: ${cronJobs.join(", ")}`] : []),
    ...(otherIntents.length > 0
      ? [
          `Extension intents: ${otherIntents
            .map((intent) => `${intent.extension} ${intent.intentKind} ${intent.key}`)
            .join(", ")}`,
        ]
      : []),
  ];

  return [
    "WARNING: This declarative schema has no pg-delta next export manifest and may have been generated by the legacy engine.",
    "pg-delta next plans to remove objects that legacy exports may omit:",
    ...detected,
    "If these removals are unintended, do not apply this migration. Re-export using pg-delta next with `supabase db schema declarative generate --overwrite` for the intended target, or add declarations for the objects you want to keep, then run sync again.",
  ].join("\n");
}
