import { describe, expect, it } from "vitest";

import {
  legacyDeclarativeCompatibilityWarning,
  legacyResolveDeclarativeMigrationName,
  legacyResolveDeclarativeSyncApplyDecision,
} from "./declarative.flow.ts";

const removals = {
  extensions: ["pgcrypto", "uuid-ossp"],
  extensionIntents: [
    { extension: "pg_cron", intentKind: "job", key: "refresh download metrics" },
    { extension: "pgmq", intentKind: "queue", key: "emails" },
  ],
};

describe("legacyDeclarativeCompatibilityWarning", () => {
  it("explains manifest-less next removals and remediation", () => {
    const warning = legacyDeclarativeCompatibilityWarning({
      implementation: "next",
      manifestPresent: false,
      removals,
    });
    expect(warning).toContain("may have been generated by the legacy engine");
    expect(warning).toContain("Extensions: pgcrypto, uuid-ossp");
    expect(warning).toContain("pg_cron jobs: refresh download metrics");
    expect(warning).toContain("Extension intents: pgmq queue emails");
    expect(warning).toContain("declarative generate --overwrite");
    expect(warning).toContain("add declarations");
  });

  it("is suppressed for next exports with a manifest", () => {
    expect(
      legacyDeclarativeCompatibilityWarning({
        implementation: "next",
        manifestPresent: true,
        removals,
      }),
    ).toBeUndefined();
  });

  it("is suppressed for the legacy engine and irrelevant removals", () => {
    expect(
      legacyDeclarativeCompatibilityWarning({
        implementation: "legacy",
        manifestPresent: false,
        removals,
      }),
    ).toBeUndefined();
    expect(
      legacyDeclarativeCompatibilityWarning({
        implementation: "next",
        manifestPresent: false,
        removals: { extensions: [], extensionIntents: [] },
      }),
    ).toBeUndefined();
  });
});

describe("legacyResolveDeclarativeMigrationName", () => {
  it("prefers an explicit --name over --file", () => {
    expect(legacyResolveDeclarativeMigrationName("my_change", "declarative_sync")).toBe(
      "my_change",
    );
  });

  it("falls back to --file when --name is empty", () => {
    expect(legacyResolveDeclarativeMigrationName("", "declarative_sync")).toBe("declarative_sync");
  });
});

describe("legacyResolveDeclarativeSyncApplyDecision", () => {
  const base = { apply: false, noApply: false, yes: false, tty: false };

  it("skips when --no-apply is set, regardless of other flags", () => {
    expect(
      legacyResolveDeclarativeSyncApplyDecision({
        apply: true,
        noApply: true,
        yes: true,
        tty: true,
      }),
    ).toBe("skip");
  });

  it("applies when --apply is set (and --no-apply is not)", () => {
    expect(
      legacyResolveDeclarativeSyncApplyDecision({ ...base, apply: true, yes: false, tty: false }),
    ).toBe("apply");
  });

  it("applies when global --yes is set", () => {
    expect(legacyResolveDeclarativeSyncApplyDecision({ ...base, yes: true })).toBe("apply");
  });

  it("prompts when on a TTY and no apply flags are set", () => {
    expect(legacyResolveDeclarativeSyncApplyDecision({ ...base, tty: true })).toBe("prompt");
  });

  it("skips in non-interactive mode with no apply flags", () => {
    expect(legacyResolveDeclarativeSyncApplyDecision(base)).toBe("skip");
  });
});
