// Regenerates src/shared/services/image-digests.generated.ts from the Dockerfile
// pins. Each digest is read from Docker Hub and checked against every mirror
// that already carries the tag, so an image that differs across registries
// fails here rather than at pull time. Needs docker buildx.
import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { dockerfileServiceImages } from "../src/shared/services/dockerfile-images.ts";
import { mirrorImageTargets } from "./detect-unmirrored-images.ts";

const repoRoot = new URL("../../../", import.meta.url);
const target = fileURLToPath(
  new URL("../src/shared/services/image-digests.generated.ts", import.meta.url),
);

function run(command: string, args: ReadonlyArray<string>): string {
  const result = spawnSync(command, args, { encoding: "utf8" });
  if (result.error !== undefined) {
    throw new Error(`could not run ${command}: ${result.error.message}`);
  }
  if (result.status !== 0) {
    throw new Error(`${command} ${args.join(" ")} failed\n${result.stderr}`);
  }
  return result.stdout.trim();
}

// Registries throttle bursts of anonymous manifest requests; a short pause clears it.
const THROTTLE_RETRY_DELAYS_MS = [2_000, 4_000, 8_000];

// The index digest of a reference, or undefined when the registry has no such tag
// (ghcr.io answers 403 for a repository it has never seen).
function indexDigest(reference: string): string | undefined {
  const args = ["buildx", "imagetools", "inspect", reference, "--format", "{{.Manifest.Digest}}"];
  let result = spawnSync("docker", args, { encoding: "utf8" });
  for (const delay of THROTTLE_RETRY_DELAYS_MS) {
    if (
      result.error !== undefined ||
      result.status === 0 ||
      !/toomanyrequests/.test(result.stderr)
    ) {
      break;
    }
    Bun.sleepSync(delay);
    result = spawnSync("docker", args, { encoding: "utf8" });
  }
  if (result.error !== undefined) {
    throw new Error(`could not run docker: ${result.error.message}`);
  }
  if (result.status !== 0) {
    if (/: (not found|403 Forbidden)\s*$/.test(result.stderr)) {
      return undefined;
    }
    throw new Error(`docker ${args.join(" ")} failed\n${result.stderr}`);
  }
  const digest = result.stdout.trim();
  if (!/^sha256:[0-9a-f]{64}$/.test(digest)) {
    throw new Error(`unexpected digest for ${reference}: ${digest}`);
  }
  return digest;
}

function pinnedDigest(image: string): string {
  const source = `docker.io/${image}`;
  const digest = indexDigest(source);
  if (digest === undefined) {
    throw new Error(`${source} does not exist`);
  }
  for (const mirror of mirrorImageTargets(image)) {
    const mirrored = indexDigest(mirror);
    if (mirrored === undefined) {
      console.error(`not mirrored yet: ${mirror}`);
    } else if (mirrored !== digest) {
      throw new Error(`${mirror} is ${mirrored}, not ${digest} as on ${source}`);
    }
  }
  return digest;
}

const entries = dockerfileServiceImages
  .map(({ image }) => `  ${JSON.stringify(image)}: "${pinnedDigest(image)}",`)
  .join("\n");
writeFileSync(
  target,
  [
    "// Generated by scripts/refresh-image-digests.ts (pnpm images:digests); do not edit by hand.",
    "export const IMAGE_DIGESTS: Readonly<Record<string, string>> = {",
    entries,
    "};",
    "",
  ].join("\n"),
);
run(fileURLToPath(new URL("node_modules/.bin/oxfmt", repoRoot)), [
  "--config",
  fileURLToPath(new URL(".oxfmtrc.json", repoRoot)),
  target,
]);
console.log(`pinned ${dockerfileServiceImages.length} images`);
