import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { Client } from "pg";
import { afterAll, beforeAll, describe, expect, test } from "vitest";

import {
  makeTempCliStackProject,
  overrideStackPorts,
  requireCliSuccess,
  runSupabase,
} from "../../../../../../tests/helpers/cli.ts";

const CLI_COMMAND_TIMEOUT_MS = 60_000;
const STACK_START_TIMEOUT_MS = 280_000;
const CLEANUP_TIMEOUT_MS = 120_000;
const LIFECYCLE_MARGIN_MS = 30_000;
const CLEANUP_HOOK_TIMEOUT_MS = CLEANUP_TIMEOUT_MS + LIFECYCLE_MARGIN_MS;
const SCENARIO_COMMAND_TIMEOUT_MS = 280_000;
const BEFORE_ALL_TIMEOUT_MS = CLI_COMMAND_TIMEOUT_MS + STACK_START_TIMEOUT_MS + LIFECYCLE_MARGIN_MS;
const SCENARIO_TIMEOUT_MS = 600_000;

const desiredSchema = `create type public.transient_state as enum ('pending', 'ready');

create table public.transient_probe (
  id bigint generated by default as identity primary key,
  state public.transient_state not null default 'pending'
);

create view public.transient_probe_states as
select id, state
from public.transient_probe;
`;

function commandFailure(result: { stdout: string; stderr: string }): string {
  return `stdout:\n${result.stdout}\nstderr:\n${result.stderr}`;
}

function migrationFiles(projectDir: string): ReadonlyArray<string> {
  const migrationsDir = path.join(projectDir, "supabase", "migrations");
  return existsSync(migrationsDir)
    ? readdirSync(migrationsDir)
        .filter((file) => file.endsWith(".sql"))
        .sort()
    : [];
}

function dbPort(config: string): number {
  const match = /^\[db\]$[\s\S]*?^port = (\d+)$/mu.exec(config);
  if (match?.[1] === undefined) throw new Error("db port is missing from config.toml");
  return Number.parseInt(match[1], 10);
}

async function migrationHistory(port: number): Promise<ReadonlyArray<string>> {
  const client = new Client({
    host: "127.0.0.1",
    port,
    database: "postgres",
    user: "postgres",
    password: "postgres",
  });
  await client.connect();
  try {
    const table = await client.query<{ table_name: string | null }>(
      "select to_regclass('supabase_migrations.schema_migrations')::text as table_name",
    );
    if (table.rows[0]?.table_name === null) return [];
    const history = await client.query<{ version: string }>(
      "select version from supabase_migrations.schema_migrations order by version",
    );
    return history.rows.map((row) => row.version);
  } finally {
    await client.end();
  }
}

describe("db schema declarative sync --transient (e2e)", () => {
  let project: Awaited<ReturnType<typeof makeTempCliStackProject>> | undefined;
  let port: number | undefined;

  beforeAll(async () => {
    project = await makeTempCliStackProject("sb-pgdelta-transient-e2e-");
    const projectDir = project.dir;

    const init = await runSupabase(["init"], {
      cwd: projectDir,
      exitTimeoutMs: CLI_COMMAND_TIMEOUT_MS,
    });
    requireCliSuccess(init, "init setup");
    await overrideStackPorts(projectDir);

    const configPath = path.join(projectDir, "supabase", "config.toml");
    const config = readFileSync(configPath, "utf8");
    if (!config.includes("[experimental.pgdelta]\nenabled = true")) {
      throw new Error("init setup did not enable experimental pg-delta in config.toml");
    }
    const configured = config.replace(
      '# declarative_schema_path = "./schemas"',
      'declarative_schema_path = "./schemas"',
    );
    writeFileSync(configPath, configured);
    port = dbPort(configured);

    const schemasDir = path.join(projectDir, "supabase", "schemas");
    mkdirSync(schemasDir, { recursive: true });
    writeFileSync(path.join(schemasDir, "public.sql"), desiredSchema);
    const extensionsDir = path.join(schemasDir, "cluster", "extensions");
    mkdirSync(extensionsDir, { recursive: true });
    for (const extension of ["pg_net", "pgcrypto", "uuid-ossp"]) {
      writeFileSync(
        path.join(extensionsDir, `${extension}.sql`),
        `CREATE EXTENSION IF NOT EXISTS "${extension}" WITH SCHEMA "extensions";\n`,
      );
    }

    const start = await runSupabase(
      [
        "start",
        "--exclude",
        "studio",
        "--exclude",
        "logflare",
        "--exclude",
        "vector",
        "--exclude",
        "gotrue",
        "--exclude",
        "realtime",
        "--exclude",
        "storage-api",
      ],
      { cwd: projectDir, exitTimeoutMs: STACK_START_TIMEOUT_MS },
    );
    requireCliSuccess(start, "start setup");
  }, BEFORE_ALL_TIMEOUT_MS);

  afterAll(async () => {
    await project?.cleanup().catch(() => undefined);
    project = undefined;
  }, CLEANUP_HOOK_TIMEOUT_MS);

  test(
    "applies locally without durable migration artifacts and converges",
    { timeout: SCENARIO_TIMEOUT_MS },
    async () => {
      const projectDir = project?.dir;
      if (projectDir === undefined || port === undefined) {
        throw new Error("transient declarative sync project was not initialized");
      }

      const filesBefore = migrationFiles(projectDir);
      const historyBefore = await migrationHistory(port);
      const apply = await runSupabase(
        ["db", "schema", "declarative", "sync", "--transient", "--yes", "--experimental"],
        {
          cwd: projectDir,
          exitTimeoutMs: SCENARIO_COMMAND_TIMEOUT_MS,
        },
      );
      expect(apply.exitCode, commandFailure(apply)).toBe(0);
      expect(apply.stdout.match(/transient_probe/gu)?.length ?? 0).toBeGreaterThanOrEqual(2);
      expect(migrationFiles(projectDir)).toEqual(filesBefore);
      expect(await migrationHistory(port)).toEqual(historyBefore);

      const converged = await runSupabase(
        ["db", "schema", "declarative", "sync", "--transient", "--yes", "--experimental"],
        {
          cwd: projectDir,
          exitTimeoutMs: SCENARIO_COMMAND_TIMEOUT_MS,
        },
      );
      expect(converged.exitCode, commandFailure(converged)).toBe(0);
      expect(`${converged.stdout}${converged.stderr}`).toContain("No schema changes found");
      expect(migrationFiles(projectDir)).toEqual(filesBefore);
      expect(await migrationHistory(port)).toEqual(historyBefore);
    },
  );
});
