/**
 * Native pgAdmin schema-diff engine used by `db diff`.
 *
 * Covers the pure halves — parsing (`parsePgAdminDiffEntries`) and rendering
 * (`renderPgAdminDiff`), recomposed as `processPgAdminDiffOutput` for a single
 * whole buffer — and the container-invocation loop, `diffSchemaPgAdmin`. Shadow
 * provisioning, status lines, and the file write stay in `diff.handler.ts`.
 *
 * Each differ run's stdout is parsed and aggregated separately rather than
 * concatenated across runs and parsed once, which would turn a multi-`--schema`
 * diff, where every run parses fine on its own, into a spurious JSON
 * "trailing data" failure. See `SIDE_EFFECTS.md` for the user-facing behavior.
 */

import { Effect, Option, Result } from "effect";

import { dockerfileServiceImage } from "../../../shared/services/dockerfile-images.ts";
import { COMPOSE_PROJECT_LABEL } from "../../../command-internal/db-bootstrap/container-lifecycle.ts";
import { CLI_PROJECT_LABEL } from "../../../command-internal/docker-ids.ts";
import { DockerRun } from "../../../command-internal/docker-run.service.ts";
import { trimGoSpace } from "../shared/go-string.ts";
import { INTERNAL_SCHEMAS } from "../../../command-internal/pg-dump.env.ts";
import { DbDiffPgAdminError } from "./diff.errors.ts";

const DIFFER_IMAGE = dockerfileServiceImage("differ");

/**
 * Only the front of the buffer is trimmed, not every occurrence — a real pgAdmin4
 * output quirk (`supabase/pgadmin4#24`). Each differ run's own copy is trimmed
 * off that run's own buffer.
 */
export const PGADMIN_DESKTOP_NOTE_PREFIX = "NOTE: Configuring authentication for DESKTOP mode.\n";

/** Prepended verbatim to every rendered diff (established output contract). */
export const PGADMIN_DIFF_HEADER = `-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.`;

/** Allow-list of `DiffEntry.type` values kept in the diff. */
const PGADMIN_DIFF_TYPES = new Set([
  "extension",
  "function",
  "mview",
  "table",
  "trigger_function",
  "type",
  "view",
]);

/**
 * Uses the `s` (dotAll) flag so `.` still matches an embedded `\r` left by a
 * `\r`-driven progress bar; `scanLines` only splits on `\n`, so a line can carry
 * one of these mid-string.
 */
const PGADMIN_PROGRESS_RE = /(.*)([0-9]{2,3})%/s;

/** Splits into lines, stripping a trailing `\r` from each and any final empty line left by a trailing `\n`. */
function scanLines(text: string): ReadonlyArray<string> {
  if (text.length === 0) return [];
  const lines = text.split("\n");
  // `split("\n")` leaves a trailing empty element after a trailing newline.
  const withoutTrailingNewline = text.endsWith("\n") ? lines.slice(0, -1) : lines;
  return withoutTrailingNewline.map((line) => (line.endsWith("\r") ? line.slice(0, -1) : line));
}

/** Extracts status text from the differ's stderr progress stream, dropping percentages and non-matching lines. */
export function processPgAdminDiffProgress(stderr: string): ReadonlyArray<string> {
  const statuses: Array<string> = [];
  for (const line of scanLines(stderr)) {
    const match = PGADMIN_PROGRESS_RE.exec(line);
    if (match === null) continue;
    statuses.push(match[1] ?? "");
  }
  return statuses;
}

/** Field name is snake_case to match the differ's wire JSON key. */
interface PgAdminDiffDependency {
  readonly type?: string | null;
}

/** One `--json-diff` array element. */
interface PgAdminDiffEntry {
  readonly type?: string | null;
  readonly status?: string | null;
  readonly diff_ddl?: string | null;
  readonly group_name?: string | null;
  readonly dependencies?: ReadonlyArray<PgAdminDiffDependency | null> | null;
  readonly source_schema_name?: string | null;
}

/** See {@link isPgAdminDiffEntryElement} for the null-tolerance rule this follows. */
function isPgAdminDiffDependencyElement(value: unknown): value is PgAdminDiffDependency | null {
  if (value === null) return true;
  if (typeof value !== "object" || Array.isArray(value)) return false;
  if ("type" in value && value.type !== null && typeof value.type !== "string") return false;
  return true;
}

/**
 * Structural guard for the differ's `DiffEntry` JSON shape: a bare `null` element is
 * accepted, `null` for a declared scalar field is tolerated as its zero value, and any
 * wrong-typed field (including `dependencies[].type`) is rejected.
 */
function isPgAdminDiffEntryElement(value: unknown): value is PgAdminDiffEntry | null {
  if (value === null) return true;
  if (typeof value !== "object" || Array.isArray(value)) return false;
  if ("type" in value && value.type !== null && typeof value.type !== "string") return false;
  if ("status" in value && value.status !== null && typeof value.status !== "string") return false;
  if ("diff_ddl" in value && value.diff_ddl !== null && typeof value.diff_ddl !== "string") {
    return false;
  }
  if ("group_name" in value && value.group_name !== null && typeof value.group_name !== "string") {
    return false;
  }
  if (
    "source_schema_name" in value &&
    value.source_schema_name !== null &&
    typeof value.source_schema_name !== "string"
  ) {
    return false;
  }
  if ("dependencies" in value && value.dependencies !== null) {
    if (
      !Array.isArray(value.dependencies) ||
      !value.dependencies.every(isPgAdminDiffDependencyElement)
    ) {
      return false;
    }
  }
  return true;
}

/**
 * Parses the differ's `--json-diff` stdout into the ordered, filtered list of DDL
 * strings, trimming the DESKTOP-mode NOTE prefix off the front first. Kept separate
 * from `renderPgAdminDiff` so `diffSchemaPgAdmin` can parse and aggregate each
 * differ run's buffer individually instead of concatenating them, which would turn a
 * multi-`--schema` diff into a spurious JSON "trailing data" failure.
 */
export function parsePgAdminDiffEntries(
  stdout: string,
): Result.Result<ReadonlyArray<string>, { readonly message: string }> {
  const trimmed = stdout.startsWith(PGADMIN_DESKTOP_NOTE_PREFIX)
    ? stdout.slice(PGADMIN_DESKTOP_NOTE_PREFIX.length)
    : stdout;
  if (trimmed.length === 0) return Result.succeed([]);

  let parsed: unknown;
  try {
    parsed = JSON.parse(trimmed);
  } catch (cause) {
    return Result.fail({
      message: `failed to parse schema diff output: ${cause instanceof Error ? cause.message : String(cause)}`,
    });
  }
  // A top-level JSON `null` is treated as an empty array, matching `isPgDeltaApplyResult`.
  const entries: unknown = parsed === null ? [] : parsed;
  if (!Array.isArray(entries) || !entries.every(isPgAdminDiffEntryElement)) {
    return Result.fail({
      message: "failed to parse schema diff output: not a valid schema-diff entry array",
    });
  }

  const filteredDdls: Array<string> = [];
  for (const rawEntry of entries) {
    const entry = rawEntry ?? {};
    const status = entry.status ?? "";
    const diffDdl = entry.diff_ddl ?? "";
    if (status === "Identical" || diffDdl === "") continue;
    if (!PGADMIN_DIFF_TYPES.has(entry.type ?? "")) continue;
    const dependencies = entry.dependencies ?? [];
    if (dependencies.some((dep) => (dep?.type ?? "") === "extension")) continue;
    const groupName = entry.group_name ?? "";
    const sourceSchemaName = entry.source_schema_name ?? undefined;
    if (
      INTERNAL_SCHEMAS.includes(groupName) ||
      (sourceSchemaName !== undefined && INTERNAL_SCHEMAS.includes(sourceSchemaName))
    ) {
      continue;
    }
    const trimmedDdl = trimGoSpace(diffDdl);
    if (trimmedDdl.length > 0) filteredDdls.push(trimmedDdl);
  }

  return Result.succeed(filteredDdls);
}

/** Header-plus-join half of the differ output pipeline. */
export function renderPgAdminDiff(ddls: ReadonlyArray<string>): string {
  if (ddls.length === 0) return "";
  return `${PGADMIN_DIFF_HEADER}\n\n${ddls.join("\n\n")}\n`;
}

/**
 * Parses and renders a single whole buffer in one call. `diffSchemaPgAdmin`
 * calls the two halves directly, once per differ run, instead.
 */
export function processPgAdminDiffOutput(
  stdout: string,
): Result.Result<string, { readonly message: string }> {
  return Result.map(parsePgAdminDiffEntries(stdout), renderPgAdminDiff);
}

function pgAdminDockerReason(
  reason: "spawn" | "inspect" | "pull",
  daemonDown: boolean,
): "docker_daemon" | "image_inspect" | "registry_pull" {
  if (reason === "spawn" || daemonDown) return "docker_daemon";
  if (reason === "pull") return "registry_pull";
  return "image_inspect";
}

export interface DiffSchemaPgAdminParams {
  /** The user's database connection string. */
  readonly source: string;
  /** The shadow database's raw connection string (not built via `toPostgresURL`). */
  readonly target: string;
  readonly schema: ReadonlyArray<string>;
  /** Merged onto both docker container labels. */
  readonly projectId: string;
  /**
   * Already resolved to a network ID by the caller; never empty. The differ always
   * joins this network and never falls back to the host network.
   */
  readonly networkId: string;
  /** Linux-only `host.docker.internal:host-gateway`; empty elsewhere. */
  readonly extraHosts: ReadonlyArray<string>;
  /** Text-mode stdout sink for the `Diffing schema: <s>` / progress status lines; no-op in machine output modes. */
  readonly emitStatus: (line: string) => Effect.Effect<void>;
}

/**
 * Runs one differ container per `--schema` flag (or one run if none given). Uses
 * `runCapture`, not `runStream`, because progress arrives on stderr, which cannot be
 * streamed incrementally today — so each run's status lines print only after that
 * run's container exits, not live. The image is passed unresolved so the registry
 * resolver picks up any project-level registry override from the caller's env scope.
 */
export const diffSchemaPgAdmin = (
  params: DiffSchemaPgAdminParams,
): Effect.Effect<string, DbDiffPgAdminError, DockerRun> =>
  Effect.gen(function* () {
    const docker = yield* DockerRun;
    const labels = {
      [CLI_PROJECT_LABEL]: params.projectId,
      [COMPOSE_PROJECT_LABEL]: params.projectId,
    };
    const network = { _tag: "named" as const, name: params.networkId };
    const runs: ReadonlyArray<string | undefined> =
      params.schema.length === 0 ? [undefined] : params.schema;

    const ddls: Array<string> = [];
    for (const s of runs) {
      if (s !== undefined) yield* params.emitStatus(`Diffing schema: ${s}`);
      const cmd =
        s === undefined
          ? ["--json-diff", params.source, params.target]
          : ["--schema", s, "--json-diff", params.source, params.target];
      const result = yield* docker
        .runCapture({
          image: DIFFER_IMAGE,
          cmd,
          env: {},
          binds: [],
          workingDir: Option.none(),
          securityOpt: [],
          extraHosts: params.extraHosts,
          network,
          labels,
        })
        .pipe(
          Effect.mapError(
            (cause) =>
              new DbDiffPgAdminError({
                message: cause.message,
                reason: pgAdminDockerReason(cause.reason, cause.daemonDown),
              }),
          ),
        );
      // Emitted before the exit-code check so a failed run's status lines still print.
      for (const line of processPgAdminDiffProgress(result.stderr)) {
        yield* params.emitStatus(line);
      }
      if (result.exitCode !== 0) {
        // Non-progress stderr lines are dropped silently, even under `--debug`.
        return yield* Effect.fail(
          new DbDiffPgAdminError({
            message: `error running container: exit ${result.exitCode}`,
            reason: "differ",
          }),
        );
      }
      const stdout = new TextDecoder().decode(result.stdout);
      // Parsed per run, not concatenated across runs.
      const parsed = parsePgAdminDiffEntries(stdout);
      if (Result.isFailure(parsed)) {
        return yield* Effect.fail(
          new DbDiffPgAdminError({
            message: parsed.failure.message,
            reason: "invalid_output",
          }),
        );
      }
      ddls.push(...parsed.success);
    }

    return renderPgAdminDiff(ddls);
  });
