import { Effect, Predicate, Redacted, Schema, Scope } from "effect";
import { isSqlError, type SqlError } from "effect/unstable/sql/SqlError";
import {
  DatabaseBootstrapError,
  INTERNAL_DATABASE,
  INTERNAL_SCHEMAS,
  JWT_SECRET_SETTING,
  type DatabaseSession,
  type DatabaseSqlValue,
  type DatabaseTransaction,
} from "./DatabaseBootstrap.ts";

export interface DatabaseSqlClient {
  readonly unsafe: (
    sql: string,
    params?: ReadonlyArray<unknown>,
  ) => Effect.Effect<ReadonlyArray<Record<string, unknown>>, SqlError>;
  readonly withTransaction: <A, E, R>(
    effect: Effect.Effect<A, E, R>,
  ) => Effect.Effect<A, E | SqlError, R>;
}

const sqlFailure = (operation: string): DatabaseBootstrapError =>
  new DatabaseBootstrapError({ message: `Database bootstrap ${operation} failed` });

const mapSqlError =
  (operation: string) =>
  (error: unknown): DatabaseBootstrapError =>
    error instanceof DatabaseBootstrapError
      ? error
      : new DatabaseBootstrapError({
          message: `Database bootstrap ${operation} failed`,
          retryable:
            isSqlError(error) &&
            (error.isRetryable ||
              (operation === "connection" && Predicate.isTagged(error.reason, "UnknownError"))),
        });

const GeneratedStatementSchema = Schema.Struct({ statement: Schema.String });

/**
 * Adapts Effect SQL to the runtime-neutral bootstrap boundary. Dynamic
 * ALTER ROLE/ALTER DATABASE statements are generated by PostgreSQL's
 * parameterized format() function and are never included in mapped errors.
 */
export interface PostgresDatabaseSession extends DatabaseSession {
  readonly query: (
    statement: string,
    parameters?: ReadonlyArray<DatabaseSqlValue>,
  ) => Effect.Effect<ReadonlyArray<Record<string, unknown>>, DatabaseBootstrapError>;
}

export const makeDatabaseSessionFromSqlClient = (
  client: DatabaseSqlClient,
): PostgresDatabaseSession => {
  const executeWith = Effect.fn("PostgresDatabaseSession.execute")(function* (
    sql: string,
    parameters: ReadonlyArray<DatabaseSqlValue> = [],
  ) {
    return yield* client
      .unsafe(sql, parameters)
      .pipe(Effect.asVoid, Effect.mapError(mapSqlError("statement")));
  });

  const queryWith = Effect.fn("PostgresDatabaseSession.query")(function* (
    sql: string,
    parameters: ReadonlyArray<DatabaseSqlValue> = [],
  ) {
    return yield* client.unsafe(sql, parameters).pipe(Effect.mapError(mapSqlError("query")));
  });

  const generated = Effect.fn("PostgresDatabaseSession.generated")(function* (
    format: string,
    parameters: ReadonlyArray<DatabaseSqlValue>,
  ) {
    yield* Effect.gen(function* () {
      const rows = yield* client
        .unsafe(format, parameters)
        .pipe(Effect.mapError(mapSqlError("statement preparation")));
      const first = rows[0];
      const decoded = yield* Schema.decodeUnknownEffect(GeneratedStatementSchema)(first).pipe(
        Effect.mapError(() => sqlFailure("statement preparation")),
      );
      yield* executeWith(decoded.statement);
    });
  });

  const transaction: DatabaseTransaction = {
    execute: executeWith,
    setRolePasswords: (roles, password) => {
      const placeholders = roles.map((_, index) => `$${index + 2}::text`).join(", ");
      return generated(
        `SELECT string_agg(format('ALTER ROLE %I PASSWORD %L', role, $1::text), E';\\n') AS statement FROM unnest(ARRAY[${placeholders}]::text[]) AS role`,
        [Redacted.value(password), ...roles],
      );
    },
    setDatabaseSettings: (settings) => {
      const values = settings
        .map((_, index) => `($${index * 2 + 1}::text, $${index * 2 + 2}::text)`)
        .join(", ");
      const parameters = settings.flatMap((setting) => [
        setting.name,
        setting.name === JWT_SECRET_SETTING ? Redacted.value(setting.value) : setting.value,
      ]);
      return generated(
        `SELECT string_agg(format('ALTER DATABASE postgres SET %I TO %L', name, value), E';\\n') AS statement FROM (VALUES ${values}) AS settings(name, value)`,
        parameters,
      );
    },
  };

  return {
    execute: executeWith,
    query: queryWith,
    transaction: (use) =>
      client.withTransaction(use(transaction)).pipe(Effect.mapError(mapSqlError("transaction"))),
  };
};

/** Acquires a SQL client in the caller's scope and keeps it live with the session. */
export const makeDatabaseSessionFromAcquisition = Effect.fn(
  "PostgresDatabaseSession.fromAcquisition",
)(function* (acquire: Effect.Effect<DatabaseSqlClient, SqlError, Scope.Scope>) {
  return yield* acquire.pipe(
    Effect.map(makeDatabaseSessionFromSqlClient),
    Effect.mapError(mapSqlError("connection")),
  );
});

/**
 * Ensures the private database and service-owned schemas exist before any
 * dependent workload is started. Database creation happens outside a transaction because
 * PostgreSQL does not support CREATE DATABASE there.
 */
export const ensureInternalDatabase = Effect.fn("PostgresDatabaseSession.ensureInternalDatabase")(
  function* (
    postgres: PostgresDatabaseSession,
    openInternal: Effect.Effect<PostgresDatabaseSession, DatabaseBootstrapError, Scope.Scope>,
  ) {
    return yield* Effect.gen(function* () {
      const databases = yield* postgres.query("SELECT 1 FROM pg_database WHERE datname = $1", [
        INTERNAL_DATABASE,
      ]);
      if (databases.length === 0)
        yield* postgres.execute(`CREATE DATABASE ${INTERNAL_DATABASE} WITH OWNER postgres`);

      const internal = yield* openInternal;
      for (const schema of INTERNAL_SCHEMAS) {
        yield* internal.execute(`CREATE SCHEMA IF NOT EXISTS ${schema} AUTHORIZATION postgres`);
        yield* internal.execute(`ALTER SCHEMA ${schema} OWNER TO postgres`);
      }
    });
  },
);
