import { PgClient } from "@effect/sql-pg";
import { Context, Duration, Effect, Layer, Redacted, Schema, Scope } from "effect";
import type { SqlError } from "effect/unstable/sql/SqlError";
import {
  DatabaseBootstrapError,
  type DatabaseBootstrapSetting,
  type DatabaseSession,
  type DatabaseSqlValue,
  type DatabaseTransaction,
  runDatabaseBootstrap,
} from "../model/DatabaseBootstrap.ts";
import type { PersistedStackState } from "../state/StackState.ts";
import { StackPreparationError } from "../public/Errors.ts";
import { databaseBootstrapPlan } from "./DatabaseBootstrapCatalog.ts";

interface PostgresDatabaseSessionOptions {
  readonly host: string;
  readonly port: number;
  readonly password: Redacted.Redacted<string>;
  readonly database?: string;
  readonly connectTimeout?: Duration.Input;
}

export interface DatabaseSqlClient {
  readonly unsafe: (
    sql: string,
    params?: ReadonlyArray<unknown>,
  ) => Effect.Effect<ReadonlyArray<Record<string, unknown>>, SqlError>;
  readonly withTransaction: <A, E, R>(
    effect: Effect.Effect<A, E, R>,
  ) => Effect.Effect<A, E | SqlError, R>;
}

const sqlFailure = (operation: string): DatabaseBootstrapError =>
  new DatabaseBootstrapError({ message: `Database bootstrap ${operation} failed` });

const mapSqlError =
  (operation: string) =>
  (error: unknown): DatabaseBootstrapError =>
    error instanceof DatabaseBootstrapError ? error : sqlFailure(operation);

const GeneratedStatementSchema = Schema.Struct({ statement: Schema.String });

/**
 * Adapts Effect SQL to the runtime-neutral bootstrap boundary. Dynamic
 * ALTER ROLE/ALTER DATABASE statements are generated by PostgreSQL's
 * parameterized format() function and are never included in mapped errors.
 */
export interface PostgresDatabaseSession extends DatabaseSession {
  readonly query: (
    statement: string,
    parameters?: ReadonlyArray<DatabaseSqlValue>,
  ) => Effect.Effect<ReadonlyArray<Record<string, unknown>>, DatabaseBootstrapError>;
}

export const makeDatabaseSessionFromSqlClient = (
  client: DatabaseSqlClient,
): PostgresDatabaseSession => {
  const executeWith = (
    sql: string,
    parameters: ReadonlyArray<DatabaseSqlValue> = [],
  ): Effect.Effect<void, DatabaseBootstrapError> =>
    client.unsafe(sql, parameters).pipe(Effect.asVoid, Effect.mapError(mapSqlError("statement")));

  const queryWith = (
    sql: string,
    parameters: ReadonlyArray<DatabaseSqlValue> = [],
  ): Effect.Effect<ReadonlyArray<Record<string, unknown>>, DatabaseBootstrapError> =>
    client.unsafe(sql, parameters).pipe(Effect.mapError(mapSqlError("query")));

  const generated = (
    format: string,
    parameters: ReadonlyArray<DatabaseSqlValue>,
  ): Effect.Effect<void, DatabaseBootstrapError> =>
    Effect.gen(function* () {
      const rows = yield* client
        .unsafe(format, parameters)
        .pipe(Effect.mapError(mapSqlError("statement preparation")));
      const first = rows[0];
      const decoded = yield* Schema.decodeUnknownEffect(GeneratedStatementSchema)(first).pipe(
        Effect.mapError(() => sqlFailure("statement preparation")),
      );
      yield* executeWith(decoded.statement);
    });

  const transaction: DatabaseTransaction = {
    execute: executeWith,
    query: queryWith,
    setRolePassword: (role, password) =>
      generated("SELECT format('ALTER ROLE %I PASSWORD %L', $1::text, $2::text) AS statement", [
        role,
        Redacted.value(password),
      ]),
    setDatabaseSetting: (setting: DatabaseBootstrapSetting) => {
      const value =
        setting.name === "app.settings.jwt_secret" ? Redacted.value(setting.value) : setting.value;
      return generated(
        "SELECT format('ALTER DATABASE postgres SET %I TO %L', $1::text, $2::text) AS statement",
        [setting.name, value],
      );
    },
  };

  return {
    execute: executeWith,
    query: queryWith,
    transaction: (use) =>
      client.withTransaction(use(transaction)).pipe(Effect.mapError(mapSqlError("transaction"))),
  };
};

/** Acquires a SQL client in the caller's scope and keeps it live with the session. */
export const makeDatabaseSessionFromAcquisition = (
  acquire: Effect.Effect<DatabaseSqlClient, SqlError, Scope.Scope>,
): Effect.Effect<PostgresDatabaseSession, DatabaseBootstrapError, Scope.Scope> =>
  acquire.pipe(
    Effect.map(makeDatabaseSessionFromSqlClient),
    Effect.mapError(mapSqlError("connection")),
  );

/** Creates a scoped production session backed by the Effect PostgreSQL pool. */
const makePostgresDatabaseSession = (
  options: PostgresDatabaseSessionOptions,
): Effect.Effect<PostgresDatabaseSession, DatabaseBootstrapError, Scope.Scope> =>
  makeDatabaseSessionFromAcquisition(
    Effect.gen(function* () {
      const services = yield* Layer.build(
        PgClient.layer({
          host: options.host,
          port: options.port,
          database: options.database ?? "postgres",
          // The canonical Supabase migration demotes the bootstrap-created
          // `postgres` role. Keep the session on the init superuser so role
          // and database-setting reconciliation remains authorized.
          username: "supabase_admin",
          password: options.password,
          connectTimeout: options.connectTimeout ?? "5 seconds",
        }),
      );
      return Context.get(services, PgClient.PgClient);
    }),
  );

const INTERNAL_DATABASE = "_supabase";
const INTERNAL_SCHEMAS = ["_analytics", "_supavisor"] as const;

/**
 * Ensures the private database and service-owned schemas exist before any
 * dependent workload is started. Database creation is deliberately outside a
 * transaction because PostgreSQL does not support CREATE DATABASE there.
 */
export const ensureInternalDatabase = (
  postgres: PostgresDatabaseSession,
  openInternal: Effect.Effect<PostgresDatabaseSession, DatabaseBootstrapError, Scope.Scope>,
): Effect.Effect<void, DatabaseBootstrapError, Scope.Scope> =>
  Effect.gen(function* () {
    const databases = yield* postgres.query("SELECT 1 FROM pg_database WHERE datname = $1", [
      INTERNAL_DATABASE,
    ]);
    if (databases.length === 0)
      yield* postgres.execute(`CREATE DATABASE ${INTERNAL_DATABASE} WITH OWNER postgres`);

    const internal = yield* openInternal;
    for (const schema of INTERNAL_SCHEMAS) {
      yield* internal.execute(`CREATE SCHEMA IF NOT EXISTS ${schema} AUTHORIZATION postgres`);
      yield* internal.execute(`ALTER SCHEMA ${schema} OWNER TO postgres`);
    }
  });

/** Runs the initial bootstrap through the durable loopback database endpoint. */
export const bootstrapDatabaseAt = (
  state: PersistedStackState,
): Effect.Effect<void, DatabaseBootstrapError | StackPreparationError> =>
  Effect.gen(function* () {
    const plan = yield* databaseBootstrapPlan(state);
    const port = state.privatePorts.find(
      (assignment) =>
        assignment.workloadId === "database:database" && assignment.binding === "primary",
    )?.port;
    if (port === undefined)
      return yield* new StackPreparationError({
        message: "A persisted database private port is required for bootstrap",
      });
    const password = state.secrets["secret:database.internal.password"]?.value;
    if (typeof password !== "string" || password.length === 0)
      return yield* new StackPreparationError({
        message: "Managed database password is unavailable for bootstrap",
      });
    yield* Effect.scoped(
      Effect.gen(function* () {
        const session = yield* makePostgresDatabaseSession({
          host: "127.0.0.1",
          port,
          password: Redacted.make(password),
        });
        yield* ensureInternalDatabase(
          session,
          makePostgresDatabaseSession({
            host: "127.0.0.1",
            port,
            database: INTERNAL_DATABASE,
            password: Redacted.make(password),
          }),
        );
        yield* runDatabaseBootstrap(session, plan);
      }),
    );
  });
