# Rules to validate CSV report files

[[rule]]
pattern_regex = "^locks_.*$"
query = "SELECT count(*) > 0 AS ok FROM `%s` WHERE age > '00:02:00'"
name      = "above_threshold"
type = "time"
column    = "ok"
pass     = "✔"
fail     = "??"

[[rule]]
pattern_regex = "^locks_.*$"
query = "SELECT count(granted) > 0 AS ok FROM `%s` WHERE granted = 'f'"
name      = "above_threshold"
type = "time"
column    = "ok"
pass     = "??"
fail     = "✔"


[[rule]]
pattern_regex = "^(blocking|calls|unused_indexes|long_running_queries|outliers)_.*\\.csv$"
query = "select count(*) = 0 as ok from `%s`"
type          = "empty"
column        = "ok"
pass          = "✔"
fail          = "??"


[[rule]]
pattern_regex = "^cache_.*$"
name      = "below_threshold"
query = "select count(*) > 0 AS ok from `%s` where ratio < 0.94"
column    = "ok"
pass     = "✔"
fail     = "??"