// Generated by scripts/refresh-image-digests.ts (pnpm images:digests); do not edit by hand.
export const IMAGE_DIGESTS: Readonly<Record<string, string>> = {
  "supabase/postgres:17.6.1.167":
    "sha256:6942962433a569e87f228b4d4ab7e11db5deca64e43babb3a038443ad6c4f1bb",
  "library/kong:2.8.1": "sha256:1b53405d8680a09d6f44494b7990bf7da2ea43f84a258c59717d4539abf09f6d",
  "axllent/mailpit:v1.30.2":
    "sha256:37a38e48e9338cd7e89dfeb487f37b02ebfcd9cb23111bed2d345e79d37d6dd6",
  "postgrest/postgrest:v16.2":
    "sha256:85258123312dc496ad4c2ed832154a65e9746f84df0d6d09b44229ff9230c08e",
  "supabase/postgres-meta:v0.99.0":
    "sha256:9a079ac1c94d89629262822a4bd1902d5b1be4adb464e5a0a8fd078aaed72158",
  "supabase/studio:2026.08.24-sha-8ec45b2":
    "sha256:4905784b715cb22b265d26405067649544b40faffff89fd8dc7a28736f42afb0",
  "darthsim/imgproxy:v3.8.0":
    "sha256:0facd355d50f3be665ebe674486f2b2e9cdaebd3f74404acd9b7fece2f661435",
  "supabase/edge-runtime:v1.74.3":
    "sha256:c52405002a890ca9fcf77978671c57f3a988e03174afb277f84ac65bc917013c",
  "timberio/vector:0.53.0-alpine":
    "sha256:ca92d617e905953c3f852e7e88061f7039460e733522e3f0c21bc6ae946b2558",
  "supabase/supavisor:2.9.12":
    "sha256:464b93a60ba8c96bc06dad7f241562d6613b2a994922307717b05f432ae415c2",
  "supabase/gotrue:v2.196.0":
    "sha256:c0c25187a6b835e65a6f6e6c6b39d090e832d40e6de5186f2c038e0411944232",
  "supabase/realtime:v2.130.0":
    "sha256:002193c9ff840a4946918641901bb6aa9e2036dc9ff7590e2b11e91d1e06bf86",
  "supabase/storage-api:v1.72.1":
    "sha256:105a2584129c9600aebed6f5ac49ca4371c92b996ecd1af7179750333e9e2120",
  "supabase/logflare:1.50.6":
    "sha256:ba88b97954573852eb18524d07507724000be02dbc94e22ee32c186ea006f1b6",
  "supabase/pgadmin-schema-diff:cli-0.0.5":
    "sha256:8e21c5f8431422a90afa370e65a1a2cad2f4cc0cd65fd17d5a84df76035a6f0f",
  "supabase/migra:3.0.1663481299":
    "sha256:56fad6eaa05c408c8db8bd9cb042e12c818c74eb8a82bd57f13fa2a5ac2feb25",
  "supabase/pg_prove:3.36":
    "sha256:eda7c5e68719e9c8287e78c017118407b48df904a51c935f5ab6098b8c0bc6bc",
};
