# Approve and queue dependency PRs created by the self-hosted Renovate workflow.
name: Renovate auto-merge

on: pull_request

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    if: github.repository == github.event.pull_request.head.repo.full_name && startsWith(github.event.pull_request.head.ref, 'renovate/')
    steps:
      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.GH_APP_CLIENT_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          permission-pull-requests: write
          permission-contents: write

      - name: Check Renovate labels
        id: check
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          GITHUB_EVENT_PULL_REQUEST_HTML_URL: ${{ github.event.pull_request.html_url }}
        run: |
          set -euo pipefail
          has_labels="$(
            gh pr view "${GITHUB_EVENT_PULL_REQUEST_HTML_URL}" --json labels \
              --jq '([.labels[].name] | contains(["automerge", "dependencies", "renovate"]))'
          )"
          echo "has_labels=${has_labels}" >> "${GITHUB_OUTPUT}"

      - name: Approve a PR
        if: steps.check.outputs.has_labels == 'true'
        run: gh pr review --approve "${GITHUB_EVENT_PULL_REQUEST_HTML_URL}"
        env:
          GH_TOKEN: ${{ secrets.AUTO_APPROVE_PR_PAT }}
          GITHUB_EVENT_PULL_REQUEST_HTML_URL: ${{ github.event.pull_request.html_url }}

      - name: Enable auto-merge for Renovate PRs
        if: steps.check.outputs.has_labels == 'true'
        run: gh pr merge --auto --squash "${GITHUB_EVENT_PULL_REQUEST_HTML_URL}"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          GITHUB_EVENT_PULL_REQUEST_HTML_URL: ${{ github.event.pull_request.html_url }}
