name: Publish migra

on:
  workflow_dispatch:
    paths:
      - apps/cli-go/**
permissions:
  contents: read

jobs:
  settings:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    outputs:
      image_tag: supabase/migra:${{ steps.version.outputs.migra }}
    steps:
      - name: Setup Blacksmith Builder
        uses: useblacksmith/setup-docker-builder@v1
      - uses: useblacksmith/build-push-action@v2
        with:
          load: true
          context: https://github.com/djrobstep/migra.git
          tags: supabase/migra:builder
      - id: version
        # Replace space with equal to get the raw version string, ie. migra=3.0.1663481299
        run: |
          docker run --rm -a STDOUT supabase/migra:builder pip show migra \
          | grep 'Version' \
          | sed -E 's/Version: (.*)/migra=\1/g' \
          >> $GITHUB_OUTPUT
        shell: bash

  build_image:
    needs:
      - settings
    strategy:
      matrix:
        include:
          - runner: [ self-hosted, X64 ]
            arch: amd64
          - runner: blacksmith-4vcpu-ubuntu-2404-arm
            arch: arm64
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 180
    outputs:
      image_digest: ${{ steps.build.outputs.digest }}
    steps:
      - run: docker context create builders
      - name: Setup Blacksmith Builder
        uses: useblacksmith/setup-docker-builder@v1
      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: build
        uses: useblacksmith/build-push-action@v2
        with:
          push: true
          context: https://github.com/djrobstep/migra.git
          tags: ${{ needs.settings.outputs.image_tag }}_${{ matrix.arch }}
          platforms: linux/${{ matrix.arch }}
            }}

  merge_manifest:
    needs:
      - settings
      - build_image
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Setup Blacksmith Builder
        uses: useblacksmith/setup-docker-builder@v1
      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Merge multi-arch manifests
        env:
          IMAGE_TAG: ${{ needs.settings.outputs.image_tag }}
        run: |
          docker buildx imagetools create -t "${IMAGE_TAG}" \
          "${IMAGE_TAG}_amd64" \
          "${IMAGE_TAG}_arm64"

  publish:
    needs:
      - settings
      - merge_manifest
    # Call workflow explicitly because events from actions cannot trigger more actions
    uses: ./.github/workflows/mirror-image.yml
    with:
      image: ${{ needs.settings.outputs.image_tag }}
    secrets: inherit
defaults:
  run:
    working-directory: apps/cli-go
