# سييدي سير العِمل هذا الى تشجيل اغترادات داتادوج اصطناعي داتادوج ماسة داتادوج الخاسّة بك
# لمزيد من العلومات حول تشغيل الاختبارات الاصطناعية ضمن سير عمل GitHub الخاص بك، راجع: https://docs.datadoghq.com/synthetics/cicd_integrations/github_actions/

# يسسسستخدم سير العمل هذا إجراءات جِير معتمدة بواسطة GitHub.
# يتم توفيرها من قبل طرف ثالث وتخضع لـ
# شروط الخدمة وسياسة الخصوصية والدعم منفصلة
# التوثيق.

# للبدء:

#1. اضف واجها برمجة تجيقات داتادوج (DD_API_KEY) وممتتاح اتجيق (DD_APP_KEY) كصدار صلى صلى صلى صلى صلى الله عليه وسلم GitHub الخاس بك. لمزيد من المعلومات، انظر: https://docs.datadoghq.com/account_management/api-app-keys/.
#2. ابدأ باستخدام الإجراء ضمن سير عملك

#Modify هذه العلامة تناسب استراتيجية الوسم الخاصة بك: اسم

الأسرار.مفتاح التطبيق DD:
تعديل هذه العلعلام٩ ت٪ناسب استراتيجي٩ الوسم الخاصة بك
على#Modify هذه العلامة تناسب استراتيجية الوسم الخاصة بكModify هذه العلامة تناسب استراتيجية الوسم الخاصة بك: [ "تطوير" ]
  طلب سحب طلب سحب طلب سحب طلب سحب:
    الفروع: [ "تطوير" ]

وظائف:
  بناء:
    يعمل على: أوبونتو-الأحدث

    خطوات:
    - الاستخدامات: الإجراءات/checkout@v4

    #كم بتشغيل الللاختبارات اللللاصطناعي٩ ضمن سير عمل GitHub الخاص بك.
    # للحصول على خيارات تكوين إضافية، قم بزيارة الإجراء داخل السوق: https://github.com/marketplace/actions/datadog-synthetics-ci
    - اسم: تشجيل استبارات داتادوج الاصطناعية
      الاستخدامات: DataDog/synthetics-ci-github-action@87b505388a22005bb8013481e3f73a367b9a53eb # الإصدار 1.4.0
      مع:
        api_key: ${{الأسرار.مفتاح واجهة برمجة التطبيقات DD}}
        مفتاح التطبيق: ${{الأسرار.مفتاح التطبيق DD}}
        استعلام البحث الاختباري: 'tag:e2e-tests' #Modify هذه العلامة تناسب استراتيجية الوسم الخاصة بك


