# يستخدم سير العمل هذا إجراءات غير معتمدة بواسطة GitHub.
# يتم توفيرها من قبل طرف ثالث وتخضع لـ
# شروط الخدمة وسياسة الخصوصية والدعم منفصلة
# التوثيق.

# سيقوم سير العمل هذا بتثبيت Deno ثم تشغيل `deno lint` و`deno test`.
# لمزيد من المعلومات انظر: https://github.com/denoland/setup-deno

اسم: دينو

على:
  يدفع:
    الفروع: ["تطوير"]
  طلب سحب:
    الفروع: ["تطوير"]

الأذونات:
  محتويات: قراءة

وظائف:
  امتحان:
    يعمل على: أوبونتو-الأحدث

    خطوات:
      - اسم: إعداد المستودع
        الاستخدامات: الإجراءات/checkout@v4

      - اسم: إعداد دينو
        # الاستخدامات: دينولاند/setup-deno@v1
        الاستخدامات: دينولاند/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        مع:
          نسخة دينو: الإصدار 1.x

      # قم بإلغاء تعليق هذه الخطوة للتحقق من استخدام 'deno fmt' في كل عملية التزام.
      # - الاسم: التحقق من التنسيق
      # تشغيل: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A
