name: Prod Deploy

on:
  # Run this action every Tuesday at 02:00 UTC (Singapore 10AM)
  schedule:
    - cron: "0 2 * * 2"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.GH_APP_CLIENT_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - run: "gh pr create -B main -H develop --title 'chore: production deploy' --label 'do not merge' --fill"
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
