name: Check Deploy

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - main

jobs:
  check:
    if: github.head_ref != 'develop'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Pull requests to main branch are only allowed from develop branch."
          exit 1
