name: Release

on:
  workflow_dispatch:
    inputs:
      channel:
        description: Release channel
        required: true
        type: choice
        options:
          - alpha
          - stable
      version:
        description: npm package version to publish
        required: true
        type: string
      dry_run:
        description: Dry run (skip actual publishing)
        required: false
        type: boolean
        default: true

jobs:
  release:
    uses: ./.github/workflows/release-shared.yml
    with:
      version: ${{ inputs.version }}
      shell: ${{ inputs.channel == 'alpha' && 'next' || 'legacy' }}
      npm_tag: ${{ inputs.channel == 'alpha' && 'alpha' || 'latest' }}
      prerelease: ${{ inputs.channel == 'alpha' }}
      dry_run: ${{ inputs.dry_run }}
    secrets: inherit
